# 衣{#cloth}

人靠衣装马靠鞍，穿着对每个自己不在意穿着的人都是很麻烦的，因为总有人告诉你得注意着装。虽然人是恒温动物，但在现代国家基本把人居环境都通过能源供给调成了室温，从家里到交通工具再到工作单位再到交通工具再到家里，到处都有空调。如果你忍得了几分钟从室内到交通工具内的室外环境，衣着上一年四季都是春秋款，但时尚人士则会把这几分钟的穿着当成自己的职业追求。衣服一定是配人的，谈吐气质是底子，买衣服穿衣服不要看品牌，特别是牌子明显的，先看天气，贴身衣物一定选舒服的，经典款不出错就够了。

本章首先介绍下面料方便选舒服的衣物，然后给出流动人口穿衣的422原则，之后简单说下场合着装防止太离谱的行为，然后就分别介绍下不同衣物配饰的选择原则。

## 面料

- 化纤、棉、麻最常见
- 蚕丝、皮草、羊绒中高档
- 棉质多次洗涤会变硬、麻料容易皱、蚕丝容易缩水、化纤无敌但怕火
- 棉料支数高好，绒长而细，透气光泽好
- 羊绒衣服需要休息回弹
- 蛋壳内有蛋白酶，可与抹布一起煮去除污渍

## 422原则

42件衣物分两周轮回，标注*2表示如果居住时间大于一年，可在安定后将对应项目翻倍，42件衣服大概占用一个半托运行李，大致包括了四季的衣服。如果携带枕头、床单与被子，那么出行所有衣物将占满托运行李。衣物总开支年化1600美元或10000人民币。

    1套西服两件套
    2套正装衬衣
    2套休闲衬衣*2
    2条休闲裤*2
    1条运动裤*2
    1条家居裤*2
    1件连帽衫*2
    1件外套*2
    1件硬壳*2
    1件软壳*2
    3件短袖*2
    
    14双袜子*1.5
    1套薄长袖内衣*2
    1套厚长袖内衣
    3条内裤*2
    
    1双皮鞋
    1双休闲鞋*2
    1双运动鞋*2
    
    1条腰带*2
    1条领带*2
    1双手套
    1顶帽子
    1条泳裤
    
## 场合着装

### 正式场合

- 西装
- 衬衣
- 皮鞋
- 配饰

### 职业场合

- 制服
- 休闲西装、衬衣

### 休闲场合

- 套头衫运动裤
- 登山套装，冲锋衣
- 游泳

### 家居

- 睡衣
- 家居服

## 帽子

- 冬天保暖绒线帽
- 夏天遮阳棒球帽
- 游泳泳帽

## 眼镜

- 镜框材料：板材或纯钛
- 镜片选择：树脂且薄
- 瞳距（PD）
- 度数：日常可以低50
- 镜腿长度挂耳
- 欧美款需要鼻托

## 领带

- 与衬衣对比
- 手打领带

## 腰带

- 头层牛皮深色
- 无logo简约款

## 袜子

- 正装配长袜
- 运动鞋配船袜或不穿
- 一天一换
- 五指袜舒服

## 鞋

- 正装牛津鞋德比鞋
- 日常板鞋运动鞋皮鞋
- 家里拖鞋
- 宽度要适合
- 跑鞋要有技术保护膝盖

## 包

- 日常买菜军用背包
- 旅行用PC拉杆箱
- 周末出行小挎包

## 表

- 正装配机械表
- 其余场合光动能电子表
- 生物钟
