# 食{#food}

## 买菜的游戏

学生时代一般人都是三点一线，食堂、实验室、宿舍。由于研究所局促的用地，我的研究生时代是三位一体，食堂、实验室、宿舍都在一个小院子里，那时两三个月去一趟超市是比较正常的，被扫地出门时行李两个箱子都装不满。但跑到国外就瞬间发现，学校食堂是不存在的，最多就是披萨、三明治跟咖啡为代表的快餐店，那玩意吃上一个星期就彻底够了，而且也不便宜。我不理解为什么他们中午就吃那么一点点蔬菜沙拉，然后却在下午吃薯片，这不是自欺欺人吗。有位朋友每天严格计算2000大卡的能量摄入，推崇吃的少而精，这无可厚非，但2000这个数就跟平均人一样是客观不存在的，而且卡路里跟营养均衡也是两个概念。我的饮食观念很简单，饿不死为底线，其他随意，但不能一成不变，因此日程里就必须要有买菜这一项。

买菜的重要性我在国内从没意识到，因为那时候我只控制一个月总伙食费，至于原料多少钱没概念。所以刚到这边超市看到菜价我是一头雾水，然后我就抽出一个周末把周边所有超市都转了一遍，之后就没有一头雾水了，而是感觉掉到马里亚纳海沟了。国内的常识是菜市场最便宜，平价超市其次，商场里的超市贵些，最贵的是景区。这个很好理解，地段租金还有稀缺都是动因，而且价差不会太大，最多就是有的打折有的原价。但在加拿大大农村，价格定的可以说是相当随意，一瓶2L可乐可以卖1加元，可以买1.99加元，也可以卖5加元，这个波动可以发生在同一家超市，也可以发生在不同超市。而且促销广告与会员卡制度的存在让价格比对变得十分困难，你可以匹配价格，但永远不知道这个东西究竟应该卖多少。

名义上超市是有阶层划分的，工薪会去沃尔玛，中产则会去中等规模有会员体系的超市而还有些超市显然卖的是服务，要不然真没法解释几倍的价差。刚来时有人跟我说1元店的东西便宜，但其实1元店的利润要高于沃尔玛，因为它会去卖小包装的东西。同样的东西你去沃尔玛买大包装的均价是低于1元店的，但你在沃尔玛是买不到小包装的。沃尔玛的定位是大卖场，但其实品类全往往代表有些小众的东西比较贵，例如沃尔玛是可以买小家具的，但跟1元店比就贵出一个段位。而且小商品都是国货，一点都不担心水土不服。

**个人冰箱决定的小包装食品与cosco**

而有会员体系的超市则通常标价比较高但附带较高的返点与规则繁复的兑换规则，返点这东西可以说是中产阶级大杀器，明明你得攒半年一年才能兑换回十块二十块且为了攒点多买的东西早就超过这个数字了，但很多人还是乐此不疲。我遇到过有人反复研究薅羊毛的，但他们似乎都忘了一个问题：1年后的10块钱不是10块钱而是当前的9块多，中间有个利息问题，你为了攒点换购比较值的大宗物品算上等待利息其实根本不值。有意思的是中产阶级都自以为自己占了便宜但商家所做的就是把获客营销成本换成了用户几年都不可能兑换的虚拟可贬值无利息的积分，商家账面流水会一直非常不错，这个智商税收的漂亮。我曾经读过有关航空公司的积分体系的一篇硕士论文，里面就提到积分池一直在变大也一直有人的积分过期，因此的获利非常多。

更厉害的是，商家玩的是混合策略，哪怕你看穿了这一点，有些超市你还是得去，因为有些商品或品牌是特供给某一连锁品牌超市的，有积分总比啥都没有好。通过区别定价，各大连锁超市实际锁定的是一个稳定客户群体与收益率，所谓最低价保证跟匹配就是为的这个目的，本质上是价格联盟，各家报表都不差。也许你花大把时间去研究最便宜的购物策略会有经济上的收益，但这大把的时间也不是免费的，是机会成本，你可以用同样的时间去做别的，所以我经常说一定要知道自己的工作时薪，低于这个的事除非你有兴趣不要去掺合。有价格匹配就不要开车去跑另一个便宜的卖场，交通也是有成本的。所有买菜策略都是个人需求与经济承受力妥协出的结果，都有个压不下去的成本，而且买的不如卖的精，在这个分工协作世界里，经济是所有陌生人的胶水，知道自己要什么很重要。

另一个要说的就是用户体验，按说超市，特别是自助结账的那种毫无体验可言，但这边超市特别是标价很任性的那种，还是会有雇员来服务，且个性化品类也比大卖场多很多。在沃尔玛，你会看到一面墙都是冷冻食品，但比较贵的超市最多一个冷柜，但会有一面墙的所谓有机食品。很多新鲜玩意大卖场根本没有，但还是比较贵的超市会有专门的货架，他们贩卖的不仅仅是商品，还有生活方式。不过这不影响很多不健康生活方式也会有一席之地，类似薯片玉米片在任何超市都会有一排专门的货架，也都会有相对便宜的自营品牌，有需求的事干嘛不卖。你可以把去什么样的超市当成阶层标签，但阶层间需求也许没你想的差距那么大，世人皆虚伪，包括你我。

还有一类超市比较特殊，国内不知道有没有，那就是 Costco 。这类超市并不在商品上赚钱而是通过会员费赚钱，但其实它们控制了货源，每类商品可选的并不多且都是大包装。如果你一大家子是没啥问题的，但大包装存在跟会员积分同样的问题就是很多东西你不吃就过期，结果相当于多消费。同样缩小的品类与自营品类也可以保证利润，消费者有时候是乐于减少自己的选择权的，例如我这样的懒汉恨不得所有商品都一个价，一个品牌，这样我就不用浪费时间在选择上了。但同样会存在另外一群人就是喜欢对比，可以说商家都在迎合所有人的口味，如果冲突就分两个品牌运营。

一般人花在买菜与思考买菜上的钱与精力应该是相对稳定的，少思考就多花钱，多思考就少花钱但耽误时间，本质上都是钱与时间的互换，每个自由人都应该自主选择而不是被别人牵着鼻子走。自由不是任性，是更多的选择与可能性，但过分自由个人大脑是受不了的。我个人是不想把时间耗在买菜上的，但这却是我每周为数不多出门闲逛的理由，所以到了周末我还是会溜达出去，呼吸新鲜空气的同时也想看看，商家又玩了什么新把戏。

## 饮食周期表

以周为单位规划的食谱，每周末更新，保证规则下的不确定性。每月买菜开支200刀，回国人民币1000元，外出就餐与之相等，每年吃饭开支6000刀以内。

## 量化厨房

厨房的配置单

    应急食品
    瓶装水
    1套餐具
    1把烧水壶
    1把便携平底锅
    1个电饭煲
    1口带盖平底锅
    1口雪平锅
    1把铲子
    1个微波炉
    1个烤面包机
    2只浅碗
    1只深碗
    2只盘子
    1个案板
    1个称
    1个温度计
    1把菜刀
    1把砍刀
    1把水果刀
    1把剪刀
    1条擀面杖
    洗洁精
    刷碗海绵
    烤箱手套
    铝箔
    蜡纸
    厨房纸
    量杯
    开罐器
    自封袋
    抹布
    调料
        盐
        糖
        胡椒粉
        味精
        甜面酱
        干粉
        面粉
        老干妈
        腐乳
        十三香/五香粉
        油
        蕃茄酱
        麻酱/花生酱
        酱油
        蚝油
        醋
        料酒
        孜然粉
        芝麻
        葱
        姜
        蒜
        咖喱
        榨菜
        酸黄瓜
    食材
        米
        面
        面包
        水果
        牛奶
        豆腐
        冷冻菜丁
        绿叶菜
        西红柿
        芹菜
        黄瓜
        熟食
        肉


## 根号点餐法

卫生意识的崛起使得有助于促进家庭关系的合餐制受到了挑战，越来越多的地球人开始逐渐接受分餐制。但整体意识较强且具备浪漫主义的地球文明演化出了一种双赢策略，他们为每个人准备一套公用餐具与一套私用餐具，公用餐具用来把合餐制的食物转移到自己的盘子，而私用餐具则用来将美食送入摄食器官中，这样保证了卫生需求，但也满足了多样化的聚餐饮食需求。然而，制度的改进却激化了另一个选择博弈，那就是究竟需要点几个菜。

较多的菜意味着地位的提升与浪费（有记录显示个别地方存有让装有食物的餐具互相堆叠来显示好客的习俗），较少的菜则会传递一种负面的社交信号，在无数次尝试后，笔者发现当点餐时菜的数量为合餐人数加上人数开根号时（四舍六入五成双），就餐博弈可以实现纳什均衡。此时菜量大概符合就餐人所需，浪费并不明显，常见的场景是就餐宾客每人选一个，发起人再将根号部分点出，值得注意的是每人单点的甜点凉菜与主食并不计入，荤素比 1:1（不足 1 则不点荤），固液比 3:1（不足 1 则不点），凉热比 1:3（不足 1 则不点）一份三人套餐的样例如下：

    锅包肉
    清蒸鲈鱼
    大拌菜
    炒青菜
    西红柿汤
    米饭各一份

宾主达成默契后，该原则可降低点餐中的混沌与尴尬，若是分餐制，则按需点好自己吃的即可。


## 家常菜、馆子菜与年菜

家常菜小灶小油，经济适用，用料磁实。馆子菜大灶宽油，工序繁复，用料量大。年菜小灶宽油，大鱼大肉，色泽鲜亮保质期长。常见菜列表：

### 早餐

- 油条配豆腐脑
- 里脊鸡蛋夹饼
- 油条煎饼果子
- 腐乳抹馒头
- 酱肉包
- 手抓饼
- 钙奶饼干配牛奶

### 硬菜

- 大盘鸡
- 酱爆鸭
- 软炸里脊
- 红烧肉
- 孜然羊肉
- 松鼠桂鱼
- 滑蛋虾仁
- 烤串
- 煎牛排
- 烤羊排
- 烤龙虾

### 热菜

- 风味茄子
- 酸辣土豆丝
- 蒜蓉西兰花
- 豆豉鲮鱼油麦菜
- 铁板日本豆腐
- 干煸四季豆
- 宫保鸡丁
- 可乐鸡翅
- 肥牛金针菇
- 土豆烩牛肉

### 凉菜

- 老醋花生
- 水煮花生
- 油炸花生米
- 盐水毛豆
- 拍黄瓜
- 凉拌西红柿
- 乾隆白菜

### 汤

- 西湖牛肉羹
- 皮蛋瘦肉粥

### 面食

- 烤馒头片
- 重庆小面
- 港式蛋餐面
- 西红柿肉酱意面
- 肉饼
- 饺子

### 饮料

- 格瓦斯
- 桂花稠酒
- 冰镇扎啤（夏天，配烧烤）

## 隔离菜单

启用于大流行时期，每周采买一次，提前备足应急隔离食粮，包括：

- 面粉2公斤
- 大米5公斤
- 绿豆1袋
- 挂面1公斤或等量意大利面
- 方便面若干
- 水果罐头*2
- 番茄酱罐头*2
- 午餐肉罐头*2
- 冷冻蔬菜*2
- 冷冻牛肉饼1袋
- 冷冻汉堡1盒
- 麦片*2
- MAE军粮正餐1箱
- 冷餐3盒
- 冷冻水饺2袋
- 冷冻鸡柳
- 啤酒12罐
- 复合维生素
- 各类调味料
- 卤料

每周购买新鲜食材并补充上述食材的消耗，新鲜食材包括

- 鸡肉/牛肉/猪肉/鱼
- 豆腐
- 牛奶
- 鸡蛋
- 面包
- 烤鸡
- 水果
- 西红柿
- 胡萝卜
- 香肠
- 奥利奥/钙奶饼干
- 果汁
- 碳酸饮料
- 零食（玉米片、糖果或洋葱圈）

早餐牛奶奥利奥或牛奶麦片或清水挂面，工作日五天中午间隔吃军粮与冷餐，晚上自由发挥，每顿饭要有蛋白摄入，每天吃三种不同种类水果蔬菜，主食从简从略，因为基本不运动。周末做手擀面与蛋炒饭。

每周做一次味增豆腐汤，用烤箱烤一次肉/冷冻鸡柳/土豆，每周尝试一两次新菜，重新熟练一两次老菜。

每隔一周卤一锅熟食或做一次涮锅或烤肉或炸肉排，包括豆腐、肉、鸡蛋、香肠、花生。

每隔一周点一次外卖改善伙食。

每周六晚制订下周菜单，不严格执行但记录。

## 独居快手菜

简单快捷步骤少，好吃不贵营养足，一人操作。

### 炒一切

先肉后菜，绿菜焯水可清脆，菜断生即可，本来就可以生吃，加糖提鲜，加醋爽滑，加酱油上色入味，料酒去腥，辅料越碎越入味，盐可以直接加辅料上，糖醋相配，酸辣相合，可直接用老干妈，都加就是复合味。热锅凉油防粘锅，热锅热油是爆炒。

### 红烧一切

肉焯水去血沫，加料酒姜片去腥，锅里放油拍碎的姜与蒜爆香，把肉放入煎熟，加料酒、生抽、醋、糖、盐，倒入水，可加老抽调色，小火焖煮二十分钟，大火收汁。糖和老抽可用可乐或冰红茶取代，糖与料酒可以用啤酒取代，不喜欢糖醋口可不加醋但保留糖，十三香或味精可加可不加。

### 卤一切

卤肉料一包、葱姜蒜、料酒、酱油、五香粉、胡椒、干辣椒、足量盐与糖加入水中煮开，然后加入焯水过的肉、豆腐、香肠。花生与鸡蛋洗净加入，盖上盖子闷二十到四十分钟，滤出卤肉，卤汁可复用或下面条。

### 炸一切

洗净，用调料腌制，挂鸡蛋糊，面糊与面包糠，鸡蛋糊调色蓬松，面糊可以是面粉与淀粉混合，隔绝保护作用，面包糠就是切片面包放干了掰碎，起酥脆作用，油温放根筷子，有小气泡温度就够了，初炸断生食材，油温升高后复炸酥脆表面。油煎也可以，油少点。

### 烤一切

一定泡水洗净除血，姜片去腥，洋葱入味，腌制后220度烤到表面金黄，尖端容易糊要剪掉，涂上油防焦，下面铺上土豆，上面肉的油会渗下去。孜然五香粉胡椒盐不能少。

### 微波炉一切

至少40秒以上，不超过4分钟，水含量不多可以厨房纸蘸水包裹或洒水，善用内置模式间歇加热控制火候。

### 凉菜

西红柿拌糖黄瓜配酱花生油炸，凉菜核心是浇头或蘸水，葱与干辣椒切碎，盐、糖、生抽、麻酱、蚝油、醋、五香粉、味精、孜然、香油、芝麻等随性搭配。不加料酒及卤料。可用油泼增香。

### 果酱制作

洗净去核去皮，加水烧开炖煮果肉，加入过量糖析出果汁，小火慢炖，最后大火收汁冷藏。

### 蛋炒饭

鸡蛋与肉丁下锅炒好，加入隔夜饭，不够干就加盐加淀粉，炒出锅气，加入蔬菜丁与酱油，吃的时候配榨菜腐乳。

### 肉碎炒面

面加盐煮熟，蒜末蕃茄酱牛肉碎洋葱炒香后加入面继续炒干盛出即可，可加适量奶酪。

### 肉饼

单人份，100克面粉配100克肉，面粉混1克盐增加筋道，10毫升牛奶（增加蛋白，筋道），加1克泡打粉或酵母提高蓬松度，逐次加温水40-50毫升和面，做面条少加水，例如30-40毫升，做面包可多加水，饺子面加冷水。和面后醒面半小时，揉面光滑后继续醒面十五分钟。肉馅加酱油、料酒、五香粉、胡椒粉、味精，加干粉吸水，油封备用，用前拌入葱花。面饼擀为长方形，铺上肉，逐渐折叠后封口压平。平底锅撒油，两面煎熟后切开可吃。烤箱最高温5分钟翻面后5分钟，出香味即可。

### 港式餐蛋面

方便面煮熟配上火腿肠或午餐肉或虾仁，奶酪，配菜使用绿叶菜或紫菜或西红柿，煎个荷包蛋，吃时配小榨菜或酸黄瓜，不要用自带调料，仅用盐、糖与胡椒粉调味，吃辣可加适量老干妈。

### 冻菜盖饭

熟食一份（香肠或烤鸡腿）、冷菜一份、大米100克配150克水，蒸米饭前混入冷菜丁，米饭熟了放熟食闷5分钟，整体用时30分钟。吃时配老干妈或腐乳或芝麻盐。

### 味增豆腐汤

豆腐切2cm立方先放盐在开水里去味，滤出后重新加凉水一包味噌，加香肠，可同时下一把面条并加入青菜平衡营养。

### 鸡丝面包碎

吃剩的烤鸡肉撕成条，干了的法棍面包捏成块，加入少量料酒、酱油、熟芝麻，一勺老干妈，淋上一点水，微波炉1分钟，拌匀加入香油。
