# 住{#rental}

不论是暂住还是定居，住对于每个人都是基本需求，天为被窝地为床听上去很潇洒，但风湿性关节炎不是闹着玩的。

本章首先关注租房原则，也就是一年十平法，然后给出家具列表方便计算居住成本，住下来就要考虑维护，所以接着介绍下家务统筹原理。住的时候个人医疗保健很重要，所以再提供一份家庭自愈指南做参考。

## 一年十平

每个社会人的个人稳定时空被解读为只有一年十平，超出这个领域的行为都是社会化的，而政府的职责就是保护每个人一年十平领域的绝对安全与其余社会时空的规范运转。而一年十平决策原则的关键在于把所有物的交换价值都去除以使用时间或寿命与个人必须的生存空间。举例来说，一件智能终端用户端更新频率为 3 年，那么平均每年的开支就是可计算的，这个数就是用户用来进行购买决策的参考基线，围绕这个基线的价格就是最合理的。但是，如果这件物品体积超过个人生存空间平面面积的 1/10，那么就要考虑迁移成本，同样材质等方面的特殊需求也要考虑迁移成本。使用频率小于等于一年一次的商品。这些商品不具备零售价值而只具备租赁价值。

此外，租房选址上按照步行工作距离，要么里工作地点很近（5分钟），好处是睡眠充足，出行安全。要么很远（50分钟以上通勤时间），这样这部分时间可以规划出来做别的事。如果距离不远不近，则出行时间就是一种浪费。订好了房间大小跟选址后按自己月收入的1/3作为住的上限开支（包括房租水电开支）去找住的地方，如果没有说明你的职业选择有点问题，需要换工作或城市。

## 家具列表

家具可以提升生活品质，但首先要考虑经济问题，这里给出家电安全使用的参考年限方便计算家具成本：电冰箱12~16年、彩色电视机8~10年、洗衣机8年、空调器8~10年、电热水器8年、个人电脑6年、电饭煲10年、电风扇10年、微波炉10年、电熨斗9年、电子钟8年、电热毯8年、燃气灶8年、吸尘器8年、电吹风4年、电动剃须刀4年。年化开支电冰箱（180）、电视（200）、洗衣机（300）、空调（240）、电热水器（150）、个人电脑（2000）、电饭煲（20）、微波炉（40）、电风扇（15）、电熨斗（40）、燃气灶（70）、吸尘器（250）、电吹风（40）、手机（2000）、无线路由器（300）、烤箱（100）、电动牙刷（500），所以年化电器开支约为2020年的1000美金。一次性开支约3000美金，年维护成本约300美金。

    床垫
    床架
    落地灯
    灯泡
    枕头
    靠枕
    床上书桌
    插座
    被子
    床单
    板凳
    便携无线路由
    洗衣液
    肥皂
    洗发水
    浴帘
    牙刷
    毛巾
    地巾
    刮胡刀
    泡沫
    牙线
    防晒霜
    卫生纸
    湿巾
    相机
    便携三脚架
    急救包
    药
    kindle
    电脑
    背包
    手机
    硬盘
    手机支架
    压缩袋
    纸箱
    桌布
    衣架
    椅子
    投影仪
    懒人沙发
    收音机

## 家务统筹

家务存在周期性，基本按日、周、月、季、年来进行家务活动

## 家庭自愈指南

- 合理膳食，水果不断
- 疫苗打全
- 保健品基本都是伪科学，好好吃饭睡觉规律生活是王道，不搞一边作死一边狂补的养生朋克
- 小孩老人考虑补钙，不见阳光补维生素D，吃饭荤素搭配有粗粮有绿叶菜
- 外伤消毒要用75%酒精、碘酒或双氧水，包扎用邦迪、创可贴与纱布，需要剪刀
- 蚊虫叮咬跌打损伤用风油精或云南白药或老虎膏药
- 感冒清热用对乙酰氨基酚或布洛芬，后者效果强，流鼻涕加上伪麻黄碱，恢复期提高免疫力可以上维生素C泡腾片，流感打疫苗，伤风感冒喝水自愈
- 咳嗽可以吃各种清凉薄荷糖缓解，止咳靠盐酸氨溴索，有炎症考虑牛黄益金片
- 不消化吃健胃消食片或 tums
- 腹泻吃吡哌酸或 Imodium ，止泻吃蒙脱石散
- 调时差睡不好觉用褪黑素（脑白金主要成分）
- 晕车晕船药店买药
- 痔疮除痘马应龙或金缕梅喷剂
- 其余的冲热水澡睡懒觉，改善不了去医院挂号，别瞎折腾用偏方
- 每年体检

## 美国登陆

- amazon会员买家具
- Walmart买日用品
- 1元店买无技术含量产品
- 查邮箱开户优惠
- 网上网络开户
- 申请ssn
- 手机超市买卡过渡
- 银行开户
- 房租支票/汇票
- 现金500美金
- 公交卡
- 信用卡global transfer
- 自行车年卡

## 全球目录

世界很大哇！人生很短唉！东西不少哩！

本目录旨在收录方便生活在地球上的好东西，排名不分先后

### 厨房纸

吸水、控油可堆肥，用了就回不去。就厨房而言，污垢是不可能去除的，但如果每天都清理，也是累积不起来的。各大超市有售。

### 隐形眼镜

戴眼镜久了换隐形眼镜会发现新世界，所有东西都变大一号。

### 珍道具

贩卖有趣但无用的产品[网站](http://www.chindogu.com/)，W. Heath Robinson 插画与 Jacques Carelman 设计的具象化（当然我刚看过维基百科），快手红人耿哥产品的潜在销售平台。如果你仔细阅读其十大准则并认同产品，那么你多半是个无聊但有趣的人，不想改变世界也不想被世界改变。

### 军品

包括但不限于军粮、军靴、背包、飞行夹克、军大衣，即使面向民用出售的产品品质也有相当保障，皮实耐用不花哨，没有概念炒作，只有基础实用款，可以闭着眼买的系列产品。选择障碍且不关注外在的你谨慎入坑，基本进去就出不来了。

### Ctrl/Cmd+F

焦虑症患者的救星，论文研读必备，电子书对纸质书压倒性优势，当你习惯了关键词定位时，视野也会狭隘下来吧。

### 懒人沙发

泡沫小球与沙发套的简单组合，然而小球堆积形成的结构在外套的支持下具备了无限可能，当然便宜与搬家时方便才是你拥有它的真正理由，难道还不够？

### 油猴脚本

网页前端品味受不了？你绝不孤独，启动 Userscript+ ，你会发现其他人针对特定域名的修改版页面，油猴脚本的存在告诉我们，自定义是一种生活态度，人人都是自己生活的设计师。

### n倍速播放

新世界大门系列，有人用来学习新知识，有人用来重温旧体验，前者心焦焦，后者意茫茫，其实变速播放也是加密技术。

### 空耳

毫无违和感的空耳会让人产生庄周梦蝶的感觉，搞不清到底是本意为之暗自潜伏，还是娱乐时代的消遣。

### 雪平锅

泛指各种带把带嘴的铝制炖锅，加热快用途多，一锅走天下。

### 空气炸锅

小容量带风扇的烤箱，工作温度180-200度，可用来快速加热肉类或肉类半成品。

### 无线耳机

对于搞不清音质音色区别的粗人而言，耳机没有线直接避免了大量摔手机拽耳朵的尴尬，就是打电话时有种对着空气宣泄的意思，创造了一些只有你感受到的虚拟实体，次元墙源头。

### 基因检测

科学算命，了解自己的复杂性，体检替代品。

### 便携式显微镜

打开微观世界的新大门，重新认识熟悉事物，别看昆虫。

### 便携式洗衣笔

外观伪装专用，快速去污，旅行必备。

### 保险

风险均摊工具，保护隐私维持公平，商业化普惠税。
