# 读书笔记 {#tips}

## 《思考，快与慢》

- 经验自我和记忆自我，两者间没有共性

- 系统1和系统2的分工是非常高效的：代价最小，效果最好

- 瞳孔是人类思维活动的灵敏指示器

- 又累又饿的保释官容易否定保释申请，疲劳和饥饿都有可能影响他们的决定

- 我只能靠认知放松来解决，如果某个答案看起来比较熟悉，我就猜测它可能就是正确答案

- 你使用彩色字体的话，亮蓝或大红的文字会比绿、黄、灰蓝等色调更容易让人相信文字内容的真实性

- 如果你很在意自己在别人眼里是否值得信赖、是否聪明睿智，那么说话时就言简意赅吧，能用简单句的时候就别用复杂句

- 押韵的格言比没有韵脚的格言显得更加深刻

- 不断重复接触就能增加喜欢程度的现象，是一个极其重要的生理现象，可推及所有动物身上。要想在一个危机层出不穷的世界生存，一个有机体对新奇刺激应该谨慎回应，随时保持警惕和逃离的状态。若一种动物对新奇的事物没有心存戒备，其生存概率就会很低

- 我们计算的结果往往比自己想要的或需要的要多

- 大样本比小样本更精确，小样本比大样本产生极端结果的概率大

- 如果你听从自己的直觉，就常常会因为把随机事件看做是有规律的事件而犯错，我们都非常愿意相信生活中大多数事情并不是随机的

- 各种各样的证据都指向同一结论，即那些跟着系统1走的人更容易受可得性偏见的影响，比那些警惕性更高的人受影响的程度更大

- 人们总会认为两个事件（在此即为银行出纳和女权主义者）的联合出现比只出现其中一件事（银行出纳）的可能性要大，此时就出现了合取谬误

- 受试者不愿从普遍现象中推导出特殊性，这一点与他们愿意从特殊现象中归纳出普遍性如出一辙

- 只要两个数值之间的相关度不高，就会出现回归平均值的情况

- 我们人类常会为过去的憾事编造牵强的解释，并信以为真，以此来蒙蔽自己

- 运气的成分越多，从中能学到的就越少

- 我们最大限度地忽略自己的无知

- 如果一个事件果真发生了，人们就会夸大自己此前作出的预测的可能性；如果可能的事件并未发生，受试者就会错误地回忆说自己当初一直都认为此事发生的可能性不大

- 主观自信与专业文化为认知错觉提供了生存的土壤

- 系统1在信息有限的情况下也能得出结论，但我们却无从得知得出这个结论的过程有多复杂。因为有了眼见即为事实原则，所以只有眼前的条件才是最重要的。逻辑上的连贯性能给人信心，而我们在观点中表现出的主观自信也反映出系统1和系统2所构建的情景的连贯性。证据的数量和质量并不那么重要，因为即使证据十分苍白也能构建一个非常连贯的故事。对于一些最重要的信念，我们其实根本就没有什么证据来证明其合理性，我们怀有这些信念仅仅是因为我们所爱的人和所信任的人也持有同样的信念。由于所知甚少，我们对自己信念的信心是毫无缘由的——但这种信念也很重要

- 那些了解更多的人比了解少的人作出的预测强不了多少。知识最丰富的人反而常常不大可靠，原因是学到更多知识的人对自己的技能产生了一种无限放大的错觉，进而变得不切实际、过于自信

- 我们应该了解的第一点是，预测错误不可避免，因为这个世界就是不可预知的；我们应该了解的第二点是，我们不应该相信高度主观的自信就是准确性的指示器

- 如果真的想选择最合适的人选，那么你应该这样做：首先，选择一些这个岗位要求的先决条件（比如技能熟练程度、个性稳重程度、可靠性等）。不要列太多，6个左右即可。这些条件最好相对独立，同时要保证你通过一个问题就能够对这几个条件进行评估。下一步就是为每个条件都列出一些问题，并想好如何对其进行评估，分数为1~5分。你应该清楚什么情况“最弱”，什么情况“最强”。

- 理论诱导的盲区（theory-induced blindness），即一旦你接受了某个理论并将其作为一个思考工具，就很难注意到其错误

- 在没有理想的选择时，人们更愿意碰运气

- 人们的选择偏好很稳定，不会随时间推移发生改变

- 对于穷人来说，花钱就意味着损失

- 负面情绪、不负责任的父母和糟糕的反馈比好的情况更具影响力，且人们处理坏消息时比处理好消息更彻底，我们会更在意避开负面的自我定义，而不是追求正面的自我定义，不好的印象和不好的模式比好的情况更容易形成，且不易消失

- 他观察到长期健康的婚姻关系不仅仅依赖于寻求幸福，更在于避免负面的情况出现

- 人们对由于不采取行动而导致的结果，会比因行动而产生的结果有更为强烈的情绪反应（包括后悔）

- 人们极度厌恶为得到其他好处而以增加风险为代价的交易，监管风险的法律与规章充分体现了人们的这种厌恶

- 峰终定律（peak-end rule）：整体的回顾性评级可通过将最糟糕时期和最后时刻的疼痛程度的平均加权而评估出来

- 过程忽视（duration neglect）：过程的持续对所有疼痛的评估没有任何影响

- 经验自我是回答“现在疼吗”这种问题的，而记忆自我则是回答“总体如何”这种问题的。我们只有通过记忆才能保存生活体验，因此，在我们思考生命时，唯一能采取的观点来自于记忆自我

- 身体不健康对经验自我幸福的不利影响会比对生活方面的评估大很多

- 结论是贫穷使人悲惨，富有可能会提升某个人的生活满意度，但总体来说来却不能提高经验自我的幸福感

- 向学生过早地灌输金钱观会影响他们在吃巧克力时的快乐感受

- 科学的进步会使我们更加困惑

- 经济人不会受启发式、眼见即为事实、窄框架、内部意见或偏好逆转的影响，但人类却无法避免这些影响

- 小医院里，超过60%的婴儿是男婴的天数肯定应该比大医院的多，因为大样本的男女比率不太可能偏离50%。很明显，这个统计学的基本概念与人类的直觉不相符

- 人们易于高估连续事件的概率，低估非连续事件的概率

- 他们也会在“生命拯救”的说法中选择风险规避，在“生命死亡”的说法中选择风险追求

## 《人类简史》

- 黑猩猩要咀嚼生肉，每天得花上五个小时，但人类吃的是熟食，每天花上一小时就够

- 烹调让人类能吃的食物种类更多，减少所需的进食时间，还能缩小牙齿、减少肠的长度

- 讨论虚构的事物正是智人语言最独特的功能

- 食物热量超过90%的来源仍然是来自人类祖先在公元前9500年到公元前3500年间驯化的植物：小麦、稻米、玉米、马铃薯、小米和大麦

- 人到现代还有着远古狩猎采集者的心，以及远古农民的胃

- 人类以为自己驯化了植物，但其实是植物驯化了智人

- 新的农业活动得花上大把时间，人类就只能被迫永久定居在麦田旁边

- 农民常常得死守田地，双方拼个你死我活

- 这正是农业革命真正的本质：让更多的人却以更糟的状况活下去

- 奢侈品史上常有这样的情况，就是原本的奢侈品往往最后会成为必需品，而且带来新的义务

- 人类一心追求更轻松的生活，于是释放出一股巨大的力量，改变了世界的面貌，但结果并没有任何人料想得到，甚至也不是任何人所乐见的

- 采集者之所以从采集野生小麦转而自行种植小麦，可能并不是为了增加日常食物供应，而是为了支持某种神庙的建筑和运作

- 从狭隘的演化观点来看，演化成功与否的标准就在于DNA的拷贝数，于是农业革命对于鸡、牛、猪、羊来说可是一大福音

- 农业革命能学到的最重要一课，很可能就是物种演化上的成功并不代表个体的幸福

- 正是这些征收来的多余食粮，养活了政治、战争、艺术和哲学，建起了宫殿、堡垒、纪念碑和庙宇。在现代晚期之前，总人口有九成以上都是农民，日出而作、胼手胝足。他们生产出来的多余食粮养活了一小撮的精英分子：国王、官员、战士、牧师、艺术家和思想家，但历史写的几乎全是这些人的故事。于是，历史只告诉了我们极少数的人在做些什么，而其他绝大多数人的生活就是不停挑水耕田

- 《汉谟拉比法典》背后的一项重要假设，就是只要国王的臣民全部接受各自的阶级角色、各司其职，整个帝国上百万的人民就能有效合作

- 不管是汉谟拉比还是美国的开国元勋，心中都有个想象的现实，想象着这个世界有着放诸四海皆准、永恒不变的正义原则（例如平等或阶级），但这种不变的原则其实只存在于智人丰富的想象力里，只存在于他们创造并告诉彼此的虚构故事中

- 演化的基础是差异，而不是平等

- 我们相信某种秩序，并非因为它是客观的现实，而是因为相信它可以让人提升合作效率、打造更美好的社会

- 为了维持想象建构出来的秩序，必须持续投入

- 真正的犬儒主义者来说，这一切贪婪的事都毫无意义

- 对外的说法绝对要坚持它们千真万确、绝非虚构。永远要强调，这种维持社会稳定的秩序是个客观事实，是由伟大的神或是自然的法则所创造

- 在教育上也要彻底贯彻同一套原则

- 个人的真正价值是由他的社会阶级以及他人对他的看法而定

- 想象建构的秩序并非个人主观的想象，而是存在于主体之间（inter-subjective），存在于千千万万人共同的想象之中

- 在农业革命之后，社会开始变得格外复杂，另一种全新的信息类型也变得至关重要：数字

- 发明文字的目的不在于复制口语，而是想要完成一些口语没做到的事

- 大多数人都会认为只有自己社会的阶级是自然的，而其他社会的阶级分法都实在是虚假又荒谬

- 非洲人在基因上的优势（免疫力）竟造成了他们在社会上的劣势

- 历史上过去的受害者，很可能会再次受害。而历史上过去的特权分子，他们的特权也很可能依然存在

- 天生带来允许，文化造成封闭

- 想要确保“平等”，就得限制住那些较突出的人；而要人人都能“自由”，也就必然影响所有人的平等

- 这三种全球秩序，首先第一种是经济上的货币秩序，第二种是政治上的帝国秩序，而第三种则是宗教上的全球性宗教，像是佛教、基督教和伊斯兰教

- 大约4000年前，整个非洲、南亚、东亚和大洋洲都是用贝壳来交易

- 全球金钱总和为60兆美元，但所有硬币和钞票的金额加起来还不到6兆美元

- 正因为有了金钱概念，财富的转换、储存和运送都变得更容易也更便宜，后来才能发展出复杂的商业网络以及蓬勃的市场经济

- 金钱正是有史以来最普遍也最有效的互信系统

- 宗教信仰的重点是自己相信，但金钱信仰的重点是“别人相信”

- 我们爱看的是反败为胜，是小人物的胜利。然而，历史就是没有正义

- 帝国正是造成民族多样性大幅减少的主因之一

- 人类就像是一个大家庭：父母享有特权，但同时也要负责孩子的幸福

- 我们眼下正在形成的全球帝国，并不受任何特定的国家或族群管辖。就像古罗马帝国晚期，它是由多民族的精英共同统治，并且是由共同的文化和共同的利益结合。在世界各地，越来越多企业家、工程师、专家、学者、律师和经理人得到召唤，一起加入这个帝国。他们必须面对的问题，就是究竟该响应这个帝国的召唤，还是要忠于自己的国家和人民？而且，越来越多的人已经投入了帝国的一方

- 我们今天常认为宗教造成的是歧视、争端、分裂。但在金钱和帝国之外，宗教正是第三种让人类统一的力量

- 宗教必须同时具备“普世特质”和“推广特质”，多数古代宗教反而是具备“区域特质”与“排他特质”，信众只信奉当地的神灵，而且也没有意愿将信仰推己及人。据我们所知，要到了公元前1000年间，才开始出现具备普世和推广特质的宗教。这可以说是史上最重要的革命之一，对于人类的统一有重大贡献，绝不亚于帝国或金钱

- 真正让多神论与一神论不同的观点，在于多神论认为主宰世界的最高权力不带有任何私心或偏见，因此对于人类各种世俗的欲望、担心和忧虑毫不在意

- 一方面，多神教徒相信有一个至高无上、完全无私的神灵；但另一方面，多神教徒也相信有许多各有领域、心有偏见的神灵，所以对于某个神的信徒来说，很容易能相信有其他神灵存在，而且也相信其他神灵同样神通广大。多神论本质上就属于开明，很少迫害异教徒

- 多神论除了促成一神教，也促成了一些二元论的宗教。二元论宗教信奉着善与恶这两种对立力量的存在。二元论与一神论不同之处在于，他们相信“恶”也是独立存在，既不是由代表“善”的神所创造，也不归神所掌管。二元论认为，整个宇宙就是这两股力量的战场，世间种种就是两方斗争的体现

- 痛苦来自欲望；要从痛苦中解脱，就要放下欲望；而要放下欲望，就必须训练心智，体验事物的本质

- 佛教徒崇拜的并不是神祇，而是这些已经开悟而尚未成佛的人，除了希望他们协助达到涅槃的境界，也希望他们帮忙处理一些世俗的问题

- 自由人文主义最重要的诫命就是要保障这种“内心声音”的自由，不受外界的侵扰或伤害。而这些诫命统称为“人权”

- 自由人文主义追求的，是尽可能为个人争取更多自由；而社会人文主义追求的，则是让所有人都能平等

- 对某个时代的了解越透彻，反而就越难解释为什么发生了这个事件而不是那个事件。但如果对某个时期只是一知半解，就很容易受到结果影响，只看到那些最后成真的可能性

- 历史的铁则就是：事后看来无可避免的事，在当时看来总是毫不明显

- 我们之所以研究历史，不是为了要知道未来，而是要拓展视野，要了解现在的种种绝非“自然”，也并非无可避免

- 博弈理论告诉我们，在有多位参与者的时候，某些概念和行为模式可能对“所有”参与者都有害，但就是有办法继续存活下去

- 科学需要的不只是研究本身要有进展，更需要科学、政治和经济彼此相互强化

- 科学革命并不是“知识的革命”，而是“无知的革命”

- 科学还是得倚靠着种种宗教和意识形态信仰，才能取得经费，并将研究正当化

- 社会性的贫穷，指的是某些人掌握了机会，却不愿意释出给他人

- 生物性的贫穷，指的是因为缺乏食物和住所，而使人的生存受到威胁

- 死神军团受到最大的挫败在于儿童死亡率

- 就算是今天中国经济突飞猛进，很可能即将回归霸主地位，基础仍然是欧洲的生产和金融模式

- 西方政府几乎就像是资本家的工会

- 整个18世纪，贩奴的获利约为6%

- 有一些宗教（例如基督教和纳粹）杀害了数百万人，原因是出于仇恨。然而，资本主义也杀害了数百万人，原因则是出于冷漠和贪婪

- 就像农业革命一样，所谓的现代经济成长也可能只是个巨大的骗局

- 新的伦理观：消费主义

- 大富豪管理资产和投资非常谨慎，反而是没那么有钱的人，买起没那么需要的汽车和电视机却毫不手软

- 大多数人都能轻松达到资本/消费主义的理想。想要进入这种新伦理所承诺的天堂，条件就是有钱人应该继续贪婪下去，把时间投入赚更多的钱，至于一般大众则是要尽情满足自己的欲望和热情，想要什么就买什么。这是人类有史以来第一次，信众终于真的能够做到宗教要求的条件

- 现代所兴起的两大想象社群，就是“民族”和“消费大众”。民族，是国家的想象社群。而所谓消费大众，则是市场的想象社群。我们说这些社群属于“想象”，是因为过去的村落社群都是成员彼此熟识，但现代不论民族或市场，成员都不可能像过去一样彼此熟悉

- 我们比较容易体会个人的辛酸，而不是人类整体的苦难

- 核子末日的威胁促进了和平主义；和平主义大行其道，于是战争退散、贸易兴旺；贸易成长，也就让和平的利润更高，而战争的成本也更高

- 纵观历史，穷人和受压迫者之所以还能自我安慰，就是因为死亡是唯一完全公平的事

- 百忧解（Prozac）之所以让人不再沮丧，靠的就不是对任何体制的改革，而只是提高血清素的浓度

- 所谓的快乐，很可能只是让个人对意义的错觉和现行的集体错觉达成同步而已

- 哲学家不断告诫人们：“认识你自己！”但言下之意也就是一般人并不知道自己真实的自我，也因此很可能忽略了真正的快乐

- 快乐既不是主观感受到愉悦，也不是主观觉得生命有意义，反而是在于放下追求主观感受这件事

- 苦的根源既不在于感到悲伤或疼痛，也不在于感觉一切没有意义。苦真正的根源就在于“追求”主观感受这件事，不管追求的是什么，都会让人陷入持续的紧张、困惑和不满之中

- 佛教与现代生物学和新世纪运动的相同点，在于都认定快乐不在于外在条件

- 许多传统哲学和宗教（如佛教）则认为，快乐的关键在于追求真我、真正了解自己

- 苦真正的来源不在于感受本身，而是对感受的不断追求

- 智人开始超越了这些界限。自然选择的法则开始被打破，而由智慧设计（intelligent design）法则取而代之

- 或许真正该问的问题不是“我们究竟想要变成什么”，而是“我们究竟希望自己想要什么”，如果还对这个问题视若等闲，可能就是真的还没想通

## 《枪炮、病菌与钢铁》

- 欧亚大陆在开始时的巨大优势因此就变成了自1492年[8]起的巨大的领先优势——其原因是欧亚大陆独特的地理条件，而不是那里的人特别聪明

- 部落和族群的不同点是部落有固定的住所和人数更多，除此以外，还有一点也是不同的，那就是：部落是由不止一个的得到正式承认的亲属群体所组成，这些群体称为氏族，氏族之间互相通婚。土地属于某个氏族，不属于整个部落。然而，部落的人数仍然很少，每一个人都知道另外每一个人的名字和他的各种亲属关系

- 部落仍然具有一种非正式的、“平等主义的”政府制度

- 随着大约7500年前酋长管辖地的出现，人们在历史上第一次不得不学会如何经常地去和陌生人打交道而又不想把他们杀死。 对这个问题的部分解决办法，是赋予一个人即酋长以使用武力的独占权利

- 酋长管辖地带来了对集中管理的、非平等主义社会来说带有根本性质的两难处境

- 盗贼统治者为了得到公众支持而使用的最后一个方法，是制造一种为盗贼统治辩护的意识形态或宗教

- 即使在今天的民主国家里，至关重要的知识也只有少数人能够获得，他们对信息流向政府的其余部门进行控制，结果也就是对决策进行控制

- 这种关于国家形成的“水利理论”遭到了一般契约理论所遭到的同样的反对。更具体地说，它所涉及的只是复杂社会进化过程中的最后阶段。至于大规模灌溉有可能出现之前的整整几千年中，是什么推动了从族群到部落再到酋长管辖地的发展，它却只字未提

- 各大陆民族长期历史之间的显著差异，不是由于这些民族本身的天生差异，而是由于他们环境的差异

- 第一组差异是各大陆在可以用作驯化的起始物种的野生动植物品种方面的差异

- 第二组因素就是那些影响传播和迁移速度的因素，而这种速度在大陆与大陆之间差异很大

- 大陆与大陆之间传播的难易程度是不同的，因为某些大陆比另一些大陆更为孤立

- 第四组也是最后一组因素是各大陆之间在面积和人口总数方面的差异

- 所有的人类社会都拥有有发明才能的人。事情恰恰是有些环境比另一些环境提供了更多的起始物种和利用发明的更有利的条件

- 任何领域的自然实验，不管是生态领域的还是人类史领域的，生来就容易受到可能的方法论的批评

##《众病之王》

- 只有当所有其他的“人类杀手”被消灭了，癌症才成为普遍现象

- 文明并没有导致癌症，而是通过延长人类的寿命，暴露了癌症

- 这种疾病的称谓来自于希腊词语“tuphon”（众风之父）。现代词语台风（typhoon）亦来源于此

- 希波克拉底曾发表过一种深奥见解，认为癌症“最好不要治，因为这样病人活得更久”

- 每一种毒可能都是化了妆的药

- 癌症治疗必须在每一种可见迹象都消失后，仍然继续保持系统的治疗

- 宗教活动和教派活动往往基于四个元素：一位先知、一个预言、一部经书和一个启示

- 医生对死亡的气息过敏。死亡意味着失败，和疾病斗争的失败——这是他们医生的死亡，是医学的死亡，也是肿瘤学的死亡

- 著作《工人的疾病》（De Morbis Artificum Diatriba），书中记录了某些特定职业聚集型爆发的几十种疾病

- 当某一罕见事件与另一罕见事件叠加在一起时，它们之间的联系就显而易见了。比如，帕特发现了阴囊癌和烟囱清扫之间

- 试验在病人和他们的朋友圈口口相传，癌症病人开始找到皮特斯和弗雷，希望在一开始就尝试大剂量治疗，而不是在所有的传统疗法失败后才试验这种方法

- 吸烟网络研究对预防癌症的简单模式提出了严峻的挑战

- 正常的细胞都是相同的；恶性细胞各有各的毒性

- 癌症，确实是一种通路的疾病

- 花费10万美元，购买一种可以延长8个星期生命的药物，值得吗？在某种程度上，这取决于提问者是谁

##《社会动物》

- 意识决定论。意识往往并不会注意到更深层次发生的事情，以为自己就是主角，可以处理一切事情，尽管这些事情并不是它所能控制的。它所创造出的世界观只强调它能理解的那些要素，却忽略了其他部分。

- 古希腊人常说：“痛苦是通往智慧的必经之路。”

- 之所以成为现在我们这样的人，在很大程度上是因为别人成为了现在他们那样

- 如果你接受了这样的邀请，那么最好随身揣上几块压缩饼干，因为这些新时代绅士们信守的生活原则可能会让你饿个半死。他们的原则很简单：选购耐用品时无比奢侈，购买消耗品时能省则省

- 社会心理学界普遍公认的原理之一，就是行为的改变往往先于态度和感情的变化

- 由于某些原因，今天上流社会的男士主要锻炼下半身肌肉，倾向于跑步、骑车等项目，而上流社会的女士往往尽力锻炼自己的躯干、上臂和前臂，以便她们可以在整个夏季都能穿着无袖礼服，还能使出“空手碎大石”的绝招

- 朱莉娅认为单身汉总归是轻浮的，然而她又从来不跟已婚男人约会，这意味着她可以毫不犹豫爱上的男人极少

- 女人更容易被那些DNA中所含的白细胞抗原与她们自身情况差异最大的男人所吸引。互补的白细胞抗原编码被认为可以让后代拥有更完备的免疫系统

- 缺乏情感会导致毁灭性和危险性的行为。缺乏情感的人不会过上极端理性、合乎逻辑、井井有条的生活，他们的生活会很荒谬。在极端情况下，缺乏情感的人会表现出反社会的人格，对野蛮行为熟视无睹，完全无法感知别人的痛苦

- 人类正是通过情感共鸣形成了道德

- 大约4岁时，他曾连续7个月认定自己是出生于太阳的太阳生物

- 父母们只要对孩子足够好就行了。他们需要给孩子提供稳定的、可预料的生活节奏。他们要能与孩子的需求合拍，将鼓励与处罚相结合。他们要让孩子能够跟他们建立在面对压力时可以依靠的牢固情感纽带。他们要随时以身作则，成为孩子应对世上难题的现实参考，从而使孩子能够在头脑中形成潜意识模型。

- 童年期的依恋关系影响人的一生

- 个人在家庭中感觉越安全，就越有可能勇敢地冒险去探索新事物

- 高中其实是一部社会分类机器。高中存在的目的是为了使年轻人认识到他们能够融入社会结构的哪一部分

- 流言是团队建立社会准则的方式

- 大多数人会认为长着大眼睛和圆脸盘的人比自己更为虚弱且更为顺从

- 成长在贫困家庭的孩子比来自中产阶级家庭的孩子要少听到3 200万个词。平均每个小时里，中产阶级家庭的孩子会听到487句话，而在靠补助金维生的家庭环境中成长的孩子只能听到178句

- 在贫穷环境中成长”的哪些因素会造成最负面的结果。他能够容易地得出贫穷造成的最终结果，但当他尝试衡量特定变量的影响时，却发现任何单一变量都不是决定结果的因素

- 棉花糖实验表明，自我控制能力并不意味着通过坚定的意志力来抑制内心的冲动

- 首先，我们会感知到某种情况；其次，我们用理性来判断这种或那种行为是否符合我们的长远利益；再次，我们用意志力来执行我们的决定

- 理性的判断力和意志力就像肌肉，但不是那种特别发达的肌肉。某些时候，在恰当的情境下，它们能够抵御住诱惑，控制住冲动。但在许多情况下，它们的力量实在太薄弱了，完全不足以实现自律，人们只是在自欺欺人

- 匿名戒酒协会的口号“假装这样做，直到你真的能做到”

- 世俗偏见认为，雄心勃勃的人总是要超越他们身边的人，努力做得比别人更好。然而事实上，雄心勃勃的人努力的目标，往往是为了加入某个专属的圈子或是团体

- 无论父母的优点与缺陷如何，你都必须永远爱他们并尊重他们”这句话的看法时，95%的亚洲人和95%的拉美裔人都表示同意

- 整体而言，西方人往往狭隘地专注于个人行动，而亚洲人更看重背景和人际关系

- 1969年，斯里兰卡的泰米尔少数民族学生占全部自然科学类在校大学生的40%，包括工程专业大学生的48%和医学专业大学生的49%。在阿根廷，名人录上的成功商业人士中有46%的人出生于其他国家。智利75%大型产业企业的高层人士要么是移民，要么是移民的子女

- 针对25～29岁人群的调查中，亚裔美国人的大学毕业率约为54%，而土生土长的美国白人的大学毕业率则为34%

- 1997～2002年，每位科威特外交官平均有246张停车违章罚单，来自乍得、埃及、尼日利亚、苏丹、莫桑比克、巴基斯坦、埃塞俄比亚以及叙利亚的外交官们的违章罚单数量同样多得令人难以置信

- 3年以上的间隔，这种效应就会消失。这方面的理论认为，母亲们与第一个孩子交谈得更多，并且会使用更为复杂的句子。当她们在较短间隔内接二连三地生育孩子时，她们不得不分散注意力才能顾及每个孩子

- 弗林效应。1947～2002年，发达国家的智商水平以每10年增长3%的速度稳定上升。这一效应在各个国家、各个年龄段以及大量不同环境中被反复观测到，并且已经成为了“环境会影响智商”的可靠证据

- 积累大量财富与高智商之间没有任何相关性

- 除了偶尔在公路休息站逛逛商店以外，他们永远不会接近现实世界

- 杂货店通常会让顾客们首先来到果蔬区。杂货商们知道，那些首先购买健康食品的顾客将感到精神振奋，因而会在稍后的购物之旅中购买更多的垃圾食品

- 顾客们往往认为放在陈列架右侧的商品比放在左侧的质量更好

- 人们吃多少取决于多少人与他们一起进餐。独自一人吃饭时吃得最少

- 把一瓶价值30美元的酒放在一堆9美元的酒中间，它看起来就很昂贵，但把它放在149美元的酒中间，它看起来就很廉价（这就是酒店要储备那些实际上几乎没有任何人购买的超级昂贵的酒的原因）

- 微笑女性的照片使男性客户的贷款需求量提升了5%，跟将贷款利率降低5%的效果一样

- 1970年，25岁的美国人当中仅有25%从未有过婚史，而到了2005年，25岁的美国人当中已有60%从未有过婚史

- 他们对自己的独特个性有着相当执著的热情，甚至到了疯狂的程度。1950年，对一组青少年进行的性格测试——询问他们是否认为自己是一个重要的人时，12%的受试者认为自己是。20世纪80年代晚期重复这一测试的时候，80%的受试者都认为自己是

- 如今，18～34岁的美国人平均每年会收到来自父母的38000美元的资助，哈罗德也依靠父母的部分金钱资助来负担房租

- 注重实用性的人以为自己能够免受任何理性思维的影响，其实他们不过是某些已故经济学家的奴隶而已

- 量化是一切模型失效的根源

- 大卫·休谟写道：“理性是且只能是感情的奴隶，除服务并顺从于感情之外，永远不可能自诩有别的功能。”

- 政治演说的结构非常简单：前12分钟讲“你”，后12分钟讲“我”

- 归属关系，要么在成人早期阶段形成拥护某个党派的立场。一旦到了中年，很少有人会更改党派

- 那些重视“机会均等”的人似乎会成为民主党人，而那些重视“有限政府”的人似乎会成为共和党人。然而实际上，你会发现人们首先成为民主党人，然后越来越重视机会均等，或者他们首先成为共和党人，然后才越来越重视有限政府

- 尽管投票者的选择是基于情感的，但这并不意味着投票者是愚蠢或是缺乏理性的

- 绝对不能提‘家庭'，要说‘工薪家庭'”，“不要说‘花费'，要说‘投资'”，这些微妙的用词改动专门用来煽动起选民们完全不同的联想

- 所有竞选活动中的琐事其实都是触发器，它们能够在人们的大脑中触发深层的连锁反应

- 竞选活动的结构设计是为了让一个原本温和的国家变得两极分化

- 他们还必须应付自己因愤怒而产生的种种情绪，这种愤怒源自美国的中上层人士，这些人拿着体面的薪水，但却不得不把60%的税后收入用于支付子女就读私立学校的高昂学费

- 人们之间的关系变得更加松散，维持自我约束、重视他人、社会同情等习惯的人际关系网失去效力。这些影响有时对于受过良好教育的人具有解放意义，毕竟他们占据着社会资本，可以探索关系松散的新世界。但是这些影响却蹂躏着那些缺乏此类资本的人，尤其对那些没怎么接受过教育的人而言更是如此。家庭结构开始崩塌，非婚生育数量飙升，犯罪率上升，对组织和制度的信任土崩瓦解。

- 人们不再为兄弟情谊所束缚，也不会偶尔响应为集体牺牲的要求。“先人一步不吃亏”的玩世不恭的思想盛行。最终结果就是国家财政赤字的飙升，而公众却不愿为了承担财政责任而接受提高税率、削减预算等措施。双方都不相信对方能够信守承诺。两党都不相信对方能真诚地做出同心协力的牺牲举措。没有了社会信任感，政治制度退化成了一场野蛮的推搡比赛

- 生活在19世纪和20世纪、自称为“社会主义者”的思想家根本就不是真正的社会主义者，他们是统计主义者，他们把国家看得比社会更重要

- 认知革命可以培养出更多共产主义式的政治风格，经济共同体将会成为关注的焦点。来自不同阶层的人们是否能意识到他们都处在共同的事业中，抑或是阶层之间的鸿沟太宽了？共同的文化将会成为关注焦点之一。社会的核心价值能否得到表述和增强？它们能不能在国家的组织结构中被反映出来？新移民能否成功融入社会之中？在哈罗德想象出来的政治领域里，保守派会一再强调，要改变国家的文化和人们的个性是非常困难的。自由派则会坚决主张，我们仍必须用实用主义的方式放手一搏

- 管理国家的才能不可避免地等同于掌控心灵的才能

- 75%的反西方恐怖分子来自中产阶级家庭，63%的反西方恐怖分子甚至读过大学

- 恐怖主义问题是社会性的问题，而不是与物质相关的问题

- 一个族群具备足以驾驭当前环境的潜意识技能，另一个族群则根本没有机会获得这种潜意识技能

- 构建预测未来模型的能力对于未来的成功至关重要

- 如果你在生育孩子前结婚，读到高中毕业，而且找到了全职工作，那么你有98%的可能性不会生活在贫困当中。但是，很多人连这些都实现不了

- 社会流动性能够削弱阶层间的冲突，因为没有人被限定在其出生的社会阶层里度过一生

- 达沃斯的社交圈由一群富有趣味但缺乏安全感的人组成，这些人努力想挤进由那些乏味无趣但却安稳满足的人组成的圈子

- 某些佛教僧侣或天主教修女进行深层次的冥想或祈祷时，他们大脑当中负责界定自己身体范围的部分——顶叶的活跃性会下降。他们会体验到对无限空间的感知

##《伟大的博弈》

1653-1789

- 荷兰的新阿姆斯特丹 -> 英国的纽约（占领7年）
- 荷兰人抵御英国人修墙 -> wall street
- 郁金香泡沫 -> 贝壳串珠投机（类似央行作用的货币控制）
- 纽约最初为第四港口城市，费城是首都
- 亚历山大·汉密尔顿：市场说了算，鼓励投机与金融，在费城建立美国银行（类似央行）
- 托马斯·杰斐逊：憎恶投机 纽约是“人性堕落的大阴沟”
名词
- 卖空（short-selling）：卖出自己并不拥有的股票，股价下跌后购回平仓赚取差价
- 洗盘（bear raid）：内部合谋卖空股票，使持有人卖出股价下跌，内部低价购回股票平仓
- 对敲（syndicat）：合谋者之间对倒股票，创造交易量来操纵股价
- 逼空（corner）：坐庄一支股票或囤积一种商品的全部供应量，迫使其他购买者在被操纵价位上购买

1789-1807

- 汉密尔顿发行债券推动第一轮股市投机
- 证券经纪人出现 -> 《梧桐树协议》（1792经纪人价格同盟）
- 内部交易 鼻祖- 威廉·杜尔 -> 汉密尔顿救市
- 《普通公司法》股东需要承担个人责任
- 伯尔决斗汉密尔顿 伯尔通过自来水公司附加条款实际建了银行 抗衡汉米尔顿的美国银行与纽约银行
- 纽交所仿照费城交易所建立
名词
- 唐提式养老保险：所有参与者投资，一段时间后幸存者获取所有资金。涉及赌博与道德问题，可能在区块链技术下复活 
    - https://www.nytimes.com/2017/03/24/business/retirement/tontines-retirement-annuity.html?_r=0 
    - https://www.kitces.com/blog/tontine-agreement-instead-of-annuity-lifetime-income-mortality-credits-and-book-review-of-milevsky-king-williams-tontine/

1807-1837

- 伊利运河与华尔街第一次大牛市
- 利特尔投机
- 杰克逊总统不欠债造成投机狂热
- 《铸币流通令》造成经济萧条打击费城，纽约上位
- 1835年纽约大火

1837-1857

- 铁路诞生，资本发挥作用融资
- 伊利铁路：华尔街的娼妓
- 电报发明，取代旗语传递交易信息
- 丹尼尔·德鲁
- 金矿发现的投机热潮与随后的全球萧条
名词
- 可转换债券：可以变成股票的债券
- 掺水股：股票发行总量超过实际注资，分红股或股票拆分都是某种掺水股

1857-1867

- 南北战争中华尔街帮助融资
- 绿钞造成黄金交易大热，出现纽约黄金交易所
- 库克首次公募债券
- 繁华的华尔街产生快餐文化
- 船长范德比尔特的两条铁路逼空战
名词
- 格雷欣法则：劣币驱逐良币，南北战争过量发行的绿钞与金币名义等价，但大家都花绿钞，金币升值

1867-1869

- 伊利铁路股权争夺战
- 船长对战德鲁、古尔德和菲克斯
- 美国政府的腐败
- 股票自动报价机出现
- 华尔街规范股票发行流程
名词
- 联合坐庄：股份持有大户联合起来降低股票供应哄抬价格

1869-1873

- 黄金操纵案
- 金本位回归
- 库克银行破产引发欧美股市大崩溃
- 6年经济低迷
名词
- 套期保值：外贸中提前买空收货的货币，如果发生贬值可以利用买空来弥补损失

1873-1884

- 市场崩溃欧洲甩卖美国债券，美国低价购回洗劫欧洲投资人
- 美国工业化
- 雷厉风行的J·P·摩根对华尔街形象的修正
- 守财奴海蒂·格林
- 投资失败的总统格兰特写作《格兰特回忆录》，成就文学名著

1884-1901

- 黄金外流案
- 总统向J·P·摩根询问对策
- 道琼斯指数出现
- 会计准则与注册会计师制度
- 太平洋铁路大战：摩根对谢弗

1901-1914

- 纽约超过伦敦
- 铜矿危机恐慌
- 摩根扮演央行稳定市场
- 1913美联储成立

1914-1920

- 一战爆发
- 美国经济开始受影响腾飞成为最大债权国
- 18年战后短期衰退
- 大爆炸开启非凡十年，可能是无政府主义者所为

1920-1929

- 赖恩汽车股大战纽交所空头，舆论起作用
- 中产阶级提高购买力，市场过热
- 美联储斯特朗意识到危机但去世了

1929-1938

- 股灾
- 大萧条出现，不一定有关系
- 取消金本位
- 创立金融监管体制
- 《1933银行法》用联邦保险防止公众挤兑
- 老肯尼迪主持证监会
- 纽交所主席惠特尼丑闻案促进纽交所改革

1938-1968

- 二战促进美国经济增长
- 1954十年大牛市，战后高速增长
- 美林公司向中产阶级兜售股票
- 本杰明·格洛斯鲍姆创立技术分析（security analysis），关注基本面分析
- 机构投资者取代个人，促进社会保障
- 纽交所为控制单一金融风险扩散建立风险基金

1968-1987

- 局部战争造成股市恐慌
- 共同基金流行
- 计算机技术解决交易系统压力
- 投行放弃合伙人制成为公众公司
- 滞涨开启
- 经纪人固定佣金制放弃
- 纳斯达克成立
- 70年代末亨特兄弟白银投机失败
- 1987黑色星期一

1987-1999

- 分散投资导致金融危机效果减弱
- 格林斯潘的美联储
- 抵押债券 拉涅利，政府下水大而不倒，次贷危机原型
- 垃圾债券市场，四大贼王米尔肯，低估的高风险债券价值
- 格雷厄姆与巴菲特的价值投资
- 彼得林奇重视股票，多元结合，善始善终
- 索罗斯反身性
- 利弗莫尔关注人性、趋势与自己弱点
- 互联网交易
- 风险套利：预先买入潜在被收购公司的股票，收购后获利

2000-2011

- 互联网泡沫
- 9·11
- 安然世通倒闭
- 美国房地产繁荣，次贷产品出现
- 次贷危机
   - 《众魔在人间》：抵押贷款公司大肆发放次贷来赚取佣金，劣币驱逐良币，然后整个行业都大肆发放贷款，华尔街为了利润包装产品，推广次贷业务，打包后用风险掉期工具给次贷产品买保险提高评级，用债务担保凭证反复保险提高评级生产AAA债劵，风险被无限放大，高盛转嫁风险道德沦丧，评级公司狼狈为奸，政府官员得到政治献金而不管不问，格林斯潘自由主义倾向抵制监管，财长鲁宾的站队
   - 《房债》：穷人边际消费倾向大，当房价降低，他们会减少消费，富人不受影响，次贷将购买力集中到房地产，其他行业活力下降，整体收入下降，开始出现循环，最终出现违约，衰退开始，大量发放房贷推动了房价是源头，银行金融工具资产担保证券分拆风险推动发放贷款，穷人的负债成了富人的资产，社会不能对单一行业形成风气
   - 《动荡的世界》：动物精神（先天性心理倾向）的威力与次贷危机，需要重视生产率来控制经济过热
   - 《大空头》：多头逐利，盲目乐观，忽视系统风险；空头也逐利，使用价值分析，两者循环往复
   - 《行动的勇气》：民主制导致美联储决策分散，影子银行大行其道，挤兑出现在金融机构之间，提供低息贷款不被接受，找摩根大通公司救市，大面积倒闭后出台量化宽松政策，政府拖底救市买债券
   - 《金融的本质》：金融危机实际上是信心危机，美联储量化宽松是为了重塑信心，货币政策要逆风向管理
   - 《大而不倒》：现金为王，房贷机构盲目认为房价不跌，金融机构拿杠杆放大了，通过CDO把风险转给了保险业与投资人，出现挤兑与恐慌，城府最终托底
- 冰岛政府破产
- 美国制造业危机
- 欧债危机

##《规模》

- 很多现象在不同尺度上等比例放大／缩小

- 多数尺度效应符合幂律分布 $attribute = c(size)^\alpha$

- 幂律分布可写成对数线性方程

- 动物的代谢速率与体积：考虑代谢散热，代谢率应该跟体表面积成正比，则代谢率是体积的2/3次方；然而实际数据是3/4次方，更高，60年无解，新理论认为代谢率应该跟能量分布有关，也就是分形维度，人体结果近似4维，体积越大，能量越小，规模经济，克莱伯定律

- 城市人口密度与犯罪率／收入

- 2006年城市人口超过农村，世界人口扩张

- 城市规模收益递增，规模越大，人均越多，超线性缩放

- 规模经济是亚线性缩放，规模越大，人均数量越少

- 规模与尺寸相关，体型小强度大，体型大，需要能量就会特别多而超出物理限制

- 地震的震级与发生频率，震级也是对数

- 药物作用随体重2/3变化而不是线性

- 轮船阻力与长度正比，越大燃料越少，伊桑巴德设计大轮船来促进全球贸易

- 无量纲数是尺度研究的核心

- 哺乳动物的血压都是相同的，分形维度，优化与空间填充，血液物理规律限制不会出现大体型哺乳动物

- 生长被能量传递过程决定，出生时能量用于生长，成熟后用于维护

- ATP的0.65eV与1/4决定了生物的代谢，温度变化两度，生长率与死亡率上升20%-30%

- 消除心血管并延长7年，癌症消除延长3.36年，其余的都不到1年

- 发动机寿命跟哺乳动物心跳总次数差不多，体型大，节食，代谢率低，损伤低，寿命延长

- 扩张是指数的，经济、人口都曾经指数增长，借助创新

- 城市规模越大，基建人均越少，越节能，亚线性

- 城市社会经济量斜率1.15，规模越大，工资越高，GDP越高，犯罪越多，流感越多，专利越多，餐厅越多

- 城市也存在空间填充与能量供应，城市是六边形而不是分形，但自发扩张会出现分形

- 城市中邓巴数与胖尾分布，利己主义与社会空间最大填充

- 大城市与小城市每个人的双向联系人人数是基本一致的，但多样性有差异

- 全球尺度访问城市的距离与频次反比，越近，访问次数越多

- 城市发展具有先发优势，领先会持续很久

- 城市资源浪费与可持续性，纽约分级供水优势，干净

- 社会经济在城市里存在多样性与正反馈

- 城市的亚线性与经济超线性需要物质能量供应，创新是源泉

- 公司收入与人数正比

- 开放式增长中上市公司半衰期10年，5%公司存活超过30年

- 全球1亿公司，估计只有4500幸存100年，长寿公司往往业务单一人数少专精

- 公司是规模经济而不是创新与创意胜出的体现，城市则超线性发展

- 可持续性的大一统，亚线性与超线性存在崩溃点，需要循环重复范式转移的创新，且时间间隔短

- 科学是精英的而不是民主的，信噪比永远存在

##《链接》

- 还原论（reductionism）：高级运动形式还原为低级运动形式，理解细节来理解整体，重组其实很困难

- 随机网络：通过随机连接节点搭建起来的网络，当添加链接数超过临界值，网络将发生剧烈变化

- 当平均链接数超过1，游离在节点簇外的节点数呈指数下降

- 随机网络模型的直方图服从泊松分布，偏离平均值的人数随偏离程度指数下降

- 六度分隔：社交网络上任意一对节点之间平均相隔6个链接；任意两个网页之间平均相隔19次点击；食物链中物种间平均间隔2；细胞中分子间平均间隔3个化学反应；科学家合作网络中不同领域科学间之间的间隔4-6个；线虫大脑神经元之间间隔14个突触

- 节点间间隔（d）和网络中节点个数（N）的对数成正比：d = 0.35 + 2LogN

- 社会链接现在可以保持很长时间，世界不断缩小，降低了人与人间的间隔程度

- 弱关系的团聚效应：团聚系数，团体间除某个体外实际链接数与最多形成的朋友链接数，1表示朋友互联，0表示该个体是唯一链接人

- 埃尔德什数&贝肯数：科学家的合作关系网，小网络

- 添加少量链接会大大降低节点间平均间隔但并不改变团聚系数，起桥梁作用

- 枢纽节点十分重要，连接度非常高，表示万维网并不平等，存在高度集中个体，平均意义不大

- 枢纽节点的存在是随机网络与团聚模型不能解释的，属于无尺度网络，遵守幂律分布，允许大量微小事件与少量重大事件，在正态分布中，极端事件出现概率指数下降，不允许枢纽节点存在。随机网络代表是公路路网，无尺度网络代表是航空网。

- [无尺度网络](https://zh.wikipedia.org/wiki/%E6%97%A0%E5%B0%BA%E5%BA%A6%E7%BD%91%E7%BB%9C)

- 物理相变过程一些物理量遵守幂律分布，威尔逊重整化理论

- 无尺度模型出现的两个要素：生长机制与偏好链接，早期的点更多时间上存在更多的机会，节点连接时倾向于连接已经有更多节点的枢纽节点

- 后发制人：解释枢纽节点变迁的适应度模型，有更高适应度的节点被连接概率高，这样后来者就可以成功。同样适应度的节点，老的胜出；同样连接度的节点，适应度高的胜出

- 玻色-爱因斯坦凝聚（绝对零度之上的最低能态，可降低光速）：胜者通吃的量子力学原理，胜者获得绝大多数的连接而不是幂律分布中层级结构，节点对应能级，适应度越高，能级越低，最高适应度的节点能级最低，吸收绝大多数节点，此时无尺度网络消失，不再是幂律分布，而是胜者为王，windows系统

- 无尺度网络存在鲁棒性，消除80%节点依然可以工作，因为故障一般影响小节点，但低于某个阈值后网络会破碎，度指数小于等于3的无尺度网络不存在这个阈值

- 攻击枢纽节点可让无尺度网络迅速崩溃，无尺度网络可以防御随机攻击但不能防御蓄意攻击，会发生级联崩溃，但如果降低发生概率可能导致更严重的级联崩溃

- 创新传播率低于某个阈值会很快消亡，但如果高于某个值会出现指数增长，在无尺度网络上传播阈值会消失，无论如何控制，都会因为不均匀拓扑传播，这是病毒低频传播的原理，性伴侣网络也是无尺度网络，艾滋病很难消除

- 控制疾病传播的方法是寻找枢纽节点或有偏向的治疗连接度高的人，这样最低限度保障安全，存在伦理问题

- 互联网（有向无尺度网络）四块大陆：
  - 中央核心：易导航，两两互联，门户网站
  - in 网络：可以到达中央核心，但无法返回
  - out 网络：可以被中央核心连接，但无法返回，公司内网
  - 分散网络：不连接中央，也不被连接

- 互联网不是均质的，像城市与乡村，不同社区的组织拓扑结构不同

- 细胞网络的无尺度拓扑，少数分子参与多数化学反应，多数分子参与一两个反应，ATP ADP 水参与多数反应，连接度最高的最古老，可以研究进化，基因与蛋白质相互作用存在网络无尺度效应，少数蛋白控制多数基本功能

- 经济社会中少数跨界董事连接了整个经济系统，网状管理模式形成精英阶层，熟人的介绍更为可靠，市场是加权有向网络，枢纽节点容易导致级联崩溃与传播

- 网络是自组织的，枢纽节点维持信息通信

- [群体智慧可视化](http://ncase.me/crowds/zh-CN.html)

- [哈密顿环与de Bruijn graphs](https://www.nature.com/articles/nbt.2023.pdf)

##《妙趣横生博弈论》

- 他们愿意和你交易，意味着他们自认为比你聪明。

- 你可能以为自己是在参与一个博弈，但这只不过是更大的博弈中的一部分，总是存在更大的博弈

- 展望初始决策后果进行判断

- 对多学科找出背景相似性，通过统一简单的方式进行思考

- 单人决策行动自由有好处，博弈中自由可能影响参与者，此时“帮助自己的双手”

- 向内部成员灌输公平跟利他的集团比自私个人集团更少出现内部冲突，也容易解决冲突，因此具有演化生存价值

- 站在对方视角看问题，要知道他们知道的信息，不知道他们不知道的信息，目标是他们的目标而不是自己希望的目标

- 如果要冒险，越早越好，无论职业选择、投资还是约会

- 以牙还牙的博弈策略并不是击败对手，而是打平手，宽宏大量的策略优于以牙还牙，最优策略需要非理性达成

- 惩罚社会欺骗者心理上会有受益或满足，存在进化解释

- 对低价敏感的顾客承担了侦查欺骗的职能

- 克服公地问题，有效的管理机制最管用

- 自私行为与群体利益有时不冲突，两个概念

- 博弈可以齐心合力生活美好，也可以各为己利生活困顿。囚徒困境中有欺骗动机，但有些情况只要随大流就没有动机

- 纳什均衡往往是经过不断反馈后达到

- 多数人推理停止在第三层上

- 博弈行动可以序贯发生，也可能同时进行

- 向前展望，向后推理可以找到最佳行动策略

- 如果是优势策略就选择，劣势策略就剔除，最终每个参与者行动都是对方行动的最优反应

- 混合策略成功率几乎不受参与者选择影响，因为考虑了对方的所有选择

- 零和博弈中，如果让对方看穿对你不利，那么就采用随机选择的混合策略

- 为了避免随机性里的规律，需要用一个客观独立机制来进行，例如秒针

- 留出足够长时间最后出手，逼迫对方也使用随机选择

- 随机策略最好应用就是用较低监管成本促使人们遵守规则

- 惩罚不一定要跟罪行吻合，但预期惩罚与罪行吻合，例如交通罚单

- 小国家可以随机发真假导弹，但防守方需要一直开动放空体系，凭空制造了需求跟筹码来反对监管

- 改变博弈，以确保参与者采取行动能得到更好的结果，此类行动称为策略行动

- 策略行动的目的是改变其他参与者的选择而不是接受

- 科学解决是什么，艺术解决如何做

- 威胁可以通过严重后果来实现

- 为了对手动摇，先让他到灾难边缘

- 让策略可信的原则是改变博弈盈利，让遵守承诺符合自己利益，把威胁变警告，把许诺变保证；改变博弈让背弃承诺能力受限；让他人帮助遵守承诺，第三方的作用

- 博弈不一定是输赢博弈或零和博弈

- 存在承诺问题时，可以用租赁代替销售

- 冲突越大，可信信息越少

- 行胜于言

- 他们将选择促进有利信息泄露的行动，这种策略称为信号传递；他们将采取行动减少或者消除不利信息的泄露，这就是信号干扰

- 信息的可信：当且仅当拥有特定信息时，采取行动才是最佳的

- 任何愿意以这些价格购买保险的人都不是你希望为之提供保险的人

- 通常，人们认为政府机构做事拖拉和不便捷是政府没有效率的证据，但有时候它们可能是处理信息问题的有价值的策略，屏蔽掉需求不强烈的人

- 但是在信息不对称的背景下，实物津贴可能是更优的，原因在于它们是一种甄别工具

- 你做的任何事情都会传递信号，包括“不传递信号”：年轻的富豪炫耀其财富，但是年老的富豪却鄙视这种低俗的炫耀；下级官员通过炫耀权力来证明自己的地位，而真正有权力的人通过高雅的姿态来表现自己的实力；接受普通教育的人炫耀他们刻意写得工工整整的字迹，但受过良好教育的人却常常字迹潦草难以辨认；成绩一般的学生会回答老师提出的简单问题，而拔尖的学生却窘于证明自己对琐碎知识点的了解；熟人通过有礼貌地忽视对方的缺点以表示其善意，而密友则通过嘲弄般地强调这些缺点以示亲密；资质平凡的人们努力用正规的资格证书给雇主和社会留下深刻印象，但天才却常常对资格证书不屑一顾，尽管他们也曾劳神去获得资格证书；声望一般的人强烈驳斥人们对自己品行的指责，而德高望重的人却觉得对指责进行驳斥有损自己的人格。在某些情况下，你能传递出的最强有力的信号就是你不要发出信号

- 价格歧视：对于几乎所有的商品或者服务，总有一些人愿意比其他人支付更高的价格（要么是因为他们更富有、需求更迫切，要么仅仅是因为他们拥有不同的口味。只要向一个顾客生产和销售产品的代价低于该顾客愿意支付的价格，销售商就愿意为这个顾客服务，索取尽可能最高的价格。但是，这将意味着对不同的顾客群制定不同的价格

- IBM在低端打印机上增加一个芯片延长等待时间来向可以等待的家庭用户提供较低价格

- 假若早期花更多时间不仅研究什么技术适应当今需要，而且考虑什么样的技术最能适应未来，那么未来就可能获得更大的收益

- 一个短暂而严厉的执法过程，可能比一个投入同等力量开展的温和而长期的执法过程有效得多

- 假如你注定失败，你可能愿意败在一项艰巨的工作上

- 职业协会：整体来看，假如我们有可能将城市牙医的数目维持在自由市场水平以下，那么牙医的收入总和就会提高。虽然牙医们 不能向那些选择在城市行医者收取费用，不过创立一笔基金用于补贴愿意投身乡村的牙医学生，倒是符合这个职业的利益的

- 你的估价就是这样一个数字：如果你不得不支付这个价钱，你就不再在乎你是赢了还是输了这场拍卖

- 谁能在没有协议的情况下过得越好，谁就越能从讨价还价的利益馅饼中分得更大一块，任何谈判的第一步都是正确地测度利益馅饼 在上

- 虚拟罢工可能是最佳策略，工作继续，但没有收益，例如免费乘坐公交，免费航班，收入募捐，这样公司会让步，社会也不会因公司停摆出现灾难

- 为了给管理层制造痛苦，以证明他们的等待成本较低

- 讨价还价得出的协议会把较大的份额归属更加耐心的一方，这一事实对于美国而言真是非常不幸。美国的政府体制以及媒体报道，实际上都在鼓动不耐烦的情绪

- 选举的结果同等地由选举过程和选民的偏好决定

- 你应该要么提供优厚的金钱奖励，要么一分钱也不提供，只支付一点报酬可能会导致最坏的结果

- 显然，用高工资雇用一个高努力付出的专家比较合算，这样可以解决更多的问题而不用体会人多但解决不了问题的状况

##《债务与魔鬼》

- 信贷的凭空产生与非理性曾昭导致灾难

- 债务拖了经济发展的后腿

- 债务没有进入实体经济而是金融与房地产

- 准备金制度锁定货币可供应数量，10%准备金可以让100元有90元可以借贷流出市场然后转存银行又可以流通81，最终100元可以产生1000元债务

- 影子银行没有准备金制度可以无限供应，100元存入可以放大到无限体量而对实体没有帮助

- 房地产交易占信贷比重过高后多手交易并不产生实体价值而导致虚假繁荣

- 金融衍生品规模过大，脱离实体经济，这样实体经济小波动可被放大

- 顺周期效应：繁荣期信贷扩张，衰退期债务挤压，市场会被悲观情绪主导

- 减少债务需求要调控房地产，合理规划城市发展，减少贫富差距可以让穷人少举债，信贷致穷

- 可持续发展需要出口盈余国家降低储蓄投资并增加消费而债务国家要抑制房地产与金融体系的债务创造，平衡全球债务

- 债务供给方要提高准备金，监督影子银行，新钱进行全额准备金，引导债务流向实体经济

- “风险共担型抵押贷款”，购买者与购房者共通承担房价波动成为房子股东

- 处理债务积压，直升机撒钱配合准备金，直接向政府买永久无息债券

- 量化宽松从二级市场买债券会抬高资产价格，让债务积压更严重，富人获益

##《钓愚》

- 行为经济学的一般性原理为欺骗平衡，只要人们在信息或心理上存在获利空间，欺骗就一定存在

- 欺骗平衡是普遍存在的

- 信息不对称与非理性是市场机制失灵的重要原因

- 心理型的可分为两种，一种是感性，一种是认知障碍出现的错觉

- 人们只想得到觉得自己应该得到的东西而不是真正想要的东西

- 挣钱可以通过技术或误导，后者其实更常见

- 如果一个人不抓住获利机会，总会有另一个人出现

- 凯恩斯认为会经济发展后出现更多的闲暇时光，但现实却是人们更忙了，去买不需要的东西

- 金融人士利用信息差把劣质与优质产品等同推销给大众往往是危机的源头，大众则是盲目信任

- 信誉透支可以获利，所以评级机构并不靠谱

- 人人都是自我为中心的机会主义者或理想主义者，后者自我欺骗引发社会变革

- 广告是植入了叙事性思维的故事，引诱购买产品

- “人生在世，要不是让大家开开玩笑，回头来又取笑别人，那又有生么意思？”《傲慢与偏见》

- 广告更多是在引诱人们心中不切实际的欲望

- 政客的重要角色就是在公众心中植入一个关于自己的故事

- 议员的目标是取悦选民与捐赠人

- 两类人善于操纵注意力：扒手与魔术师

- 欺骗者在缺乏监管的市场中会战胜良知企业

- 大多数人都生活在平静的绝望中

- 故事可以制造稀缺

- 二手车交易中从10%傻瓜消费者赚到的利润相当于总利润的一半

- 低频大宗交易例如房子、婚丧、旅游、升学与汽车是欺骗重灾区

- 信用卡会让你花更多的钱

- 监管有时只能改变企业的欺骗方式而不是消除欺骗

- 索洛模型中没有考虑有些创新只是单纯损人利己的

- 道德社会对抗信息欺诈有成功经验

- 对于心理影响，要保持专注

- 社保的强制属性会减少个人知识不足导致的欺诈

- 证券监管需要加大对监管的投入，吸引到人才

- 选举要弱化捐助人影响改为代金券方式限制募资

- 经济学家通常只考虑外部性为市场不良的原因，但欺骗平衡是根植在市场之内的，竞争市场的衍生物

## 《叙事经济学》

最近读完了席勒2019年出版的《叙事经济学》，这本讲经济的书用的核心例子是流行病学的传播模型，结果没想到2020年就真的出了大流行。其实可以找到疫情初期美股多次熔断时席勒教授接受采访时的记录，当时采访者就拿他新书里的流行病学隐喻来提问关于可能的金融危机，感觉他回答的挺尴尬的。不过，这本书也很好继承了席勒的风格：想法优秀，表达捉急，很多人会感觉读了个谷歌书籍词频与ProQuest的使用说明书。当然确实这本书大多数例证都用了这俩工具，这么评价虽然刻薄，倒也贴切。

这本书实际上可看作他从上一本《钓愚》的衍生作品，我现在也逐渐发现点畅销书作家的套路了，第一本一定是最掏心掏肺的，不论他的《非理性繁荣》、钻石教授的《第三种黑猩猩》、塔勒布的《随机漫步的傻瓜》、道金斯的《自私的基因》还是赫拉利的《人类简史》，第一本书其实是框架最全的，后续作品都可以在第一本书里找到对应章节，然后增加案例与讨论展开变成三部或n部曲模式。这套路类似漫威宇宙电影模式，倒不是说后续作品不精彩，只是这种创作模式可能对于畅销书作家最具备可持续性。更多的滞销书作者不是不知道这个套路，但很少有人第一本书就能被大众关注，而且前面这些作者都是先混学术圈（塔勒布混资本市场，更血腥），经历过审稿人鸡蛋里挑骨头的人去写畅销书只要说人话（当然很多学术界的人天生不说人话）就不会太差。全职写作的人不缺文笔写法，但可能会缺特别专精接地气的经历，当个人经验耗尽后容易缺素材，所以我不是很认可内容创作者要全职的说法，一旦脱离生活体验，创作就会走下坡路，要是沾上抄袭洗稿的习惯就只能算个文坛快枪手了。

扯远了。在《钓愚》里，作者提出了欺骗平衡作为经济行为的一种根基，因为交易中绝大多数的套利空间都是信息不对称与非理性行为主导，非理性繁荣就是这种套利在宏观上的体现。那么这里就要解释清楚一个问题，这种套利是否可持续？《叙事经济学》的主要观点就是经济行为会受到叙事的影响，有开头，有铺垫，有高潮，有转折，然后回归正常，几乎所有的概念炒作都会经历这种涨潮退潮一地鸡毛的情况，职业套利者需要不断创造新叙事或从历史里翻出老概念才能长期套利。当然你把这推广到学术圈也没啥问题，学术界追热点更疯狂，不信你可以去数数现在关于新冠出了多少篇预印本，未来我们可以统计下最后究竟多少被发表，看看这个泡沫有多大。更直接的证据就是微博热搜，从上热搜到退下去其实非常快，很多互联网时代的明星可以没有任何拿的出手的作品或只有一两个代表作，但只要时不时上个娱乐热搜，公众就会觉得他们始终很火。他们是通过经营自己的叙事来让公众或粉丝感受到人设与真实感，如果依赖作品，那么公众印象更深的是作品剧情或角色的叙事，不利于明星后续通过自己品牌赚钱。想成为老戏骨是漫长的高风险的依赖机会的，但成为偶像经营自己人设是掌控感更强的且容易变现的，资本会运作哪一个一目了然。

又扯远了。席勒的叙事讨论是跨学科的，除了流行病学，还涉及了历史学、社会学、人类学、心理学、市场营销、心理分析与宗教研究。他发现叙事这种手段几乎无处不在，且都符合这种传染、康复、衰退的流行病学传播模式。叙事的本源在于人对于有些信息总是过度解读或自动脑补的，偶然事件给你整出个逻辑来非常轻松，因果链交织一下都能给你整出个理论体系来洗脑。席勒将这种脑补过的事实类比为星座，因为天空的星座其实并不真实存在，只是人们观星时方便记录虚构出来的东西，但星座一旦形成就有了自己的生命力。很多历史事件的真相根本不是传播中的样子，但如果因此不去分析这些事为什么失真后更有传播力会错失更多的细节。好比真实的历史是《三国志》，但《三国演义》却成了三国叙事的大本营，过五关斩六将把关羽形象烘托极为丰满但这个情节却是虚构的，吕布的方天画戟是宋代才出现的，如果我们坚持历史事实，事实上反而会忽略关羽或吕布这个历史IP在民间的形成与演化过程。

叙事起源是一回事，但真正流行开来却是另一回事，很多名人警句的出处是更早的作品，但就是因为某个名人说了，现在就都成了他的源头。又比如现在很多人都说拉杆箱是全球机组人员的首选，然后都在传飞行员90年代设计出来这个叙事，但事实上1887年就出现了轮式行李箱的专利，好的产品没有故事就很难传播，但这个故事真假却是最不重要的，直观简单又离奇的小故事格外有生命力。现在几乎所有品牌都在打造自己的品牌故事，毕竟工业品标准化大生产没啥故事性，想搞溢价必须得搞点都市传说增加逼格，不用说奢侈品是重灾区。最近两年流行的后真相与假新闻仔细分析下都有叙事背景，有的要脸的还有事实基础算是加工或片面展示，不要脸的连事实都是人工智能虚拟生成的，但这些虚假叙事你就算戳穿了也有人信。从信息熵角度，一件事发生概率越低，信息含量越高，人们传播意愿就高，一则能传播开的叙事一定是高信息量的，但辟谣相当于去传播一件事的正常化过程，发生概率变高，人们传播意愿低，天然就不如谣言传得快。哪怕你同时传播谣言与辟谣，谣言都有把握完胜，更不用说辟谣还总是慢半拍。好在互联网时代大家记性都不咋地，最后可能啥都恢复基线了。

叙事事件是会在其发展过程中实现理论自洽与贴合价值判断，从而在历史进程中被反复流行或突然关注度暴增，例如比特币本身就是技术，但如果加上无政府主义与中本聪的神秘主义并迎合当前对金融系统的不满情绪，这一叙事就会不断完善，更难被质疑，爱好者从能看明白白皮书的技术人员一下扩充到对技术一窍不通只知道概念的人，但这样的人是有上限的，当无法增长或增长的都是投机者而不是技术人员后必然衰退，投机者始终是会被其他机会概念夺走的，属于未来的技术能有经济效益也必然是在未来而不是现在，热情褪去后生活还是如常进行。叙事这种自我迭代让其特别受阴谋论者的喜欢，他们在事实加工上可以说无所不用其极。

席勒毕竟是经济学家，在引入叙事概念后他又整理了经济领域一些反复流行的叙事元素，对这些元素的分别考察将有助于我们深入理解叙事对经济活动的作用，有意思的是席勒这里把《非理性繁荣》里互联网危机前那些分析过的因素重新描述成了叙事，并用叙事交汇来描述重大经济事件的起因，也是读到这里我感觉他的新书是在换皮，不过也确实有新东西。席勒提出的九个长期经济叙事为：

- 恐慌与信心
- 节俭与炫耀性消费
- 金本位与金银复本位制
- 劳动节约型机器取代工作岗位
- 自动化与人工智能取代所有工作
- 房地产繁荣与萧条
- 股市泡沫
- 杯葛（抵制）、奸商与邪恶企业
- 工资-物价螺旋式上升与邪恶工会

对很多人而言会认为这九个叙事要么是过去的不在发生，要么是现在的，但事实上这九个都是过去反复发生且现在穿着马甲到处跑的。这里不去讨论这些叙事本身对错，席勒研究手段就是谷歌书籍关键词的历史趋势，很多经济叙事是在历史上经济系统不同领域反复横跳渐次出现传播高峰的。有些叙事事实上成了新叙事的原始版本，例如金本位与金银复本位制就与比特币密切相连，大规模失业的讨论也不是alphago出现后才有的，女性进入职场、放宽移民政策还有高效率机器的研发都曾经带动了这一失业叙事的流行。如果我们去研读大萧条时期的报纸或私人日记，会发现各种稀奇古怪的叙事，很多描述明显是情绪化的，与历史记录完全不同。其实远的就不说了，这次疫情中公众号里流行了多少叙事，很多说的时候言之凿凿，过几天就成了笑话，例如不戴口罩有理、服用双黄连还有羟氯喹预防新冠啥的，不过当大家都是局中人时，还真不一定能笑出来。历史上很多危机的解决实际也依赖了叙事的力量，特别是战争期间领导人讲话，有些鼓舞人心的东西其实是虚构的。

整体来说，叙事经济学给出了一则面向加工过事实研究的经济学思路，不同于研究客观数据，这种带有虚构成分的叙事流行现象对于了解很多经济行为提供了跨学科的理论接口，可看作行为经济学的动力学研究。不过，如同席勒所言，我们能用的定量研究叙事的工具与数据源似乎不是很多，但只要我们的流行病学或文本分析或自然语言处理技术继续发展，叙事经济学就应该会有更有意思的发现，搞不好以后想做深入的行为经济研究得入职人工智能公司或医院了。

不过，作为一个概念，叙事可以帮我们理解很多社会现象。当我们面对决策时，所依赖的更多是客观数据，但真实社会朴实无华而复杂，充斥了各种虚构与欺骗平衡，如果能捕捉到其中叙事的影子并点出来，有时候就能让很多人走出自己的逻辑闭环。另一个启示就是叙事的流行总会回归基线，没人能做到天天高能对线，考虑到可持续性就能识别很多叙事背后的泡沫。这本书里有大量的案例供参考，有精力可以去读下原文，我感觉现在很多文章强于说理但明显作者本身阅历无法支撑结论，总是抓不住重点，很多逻辑判断事实根本不成立。想来想去应该就是过度强调模型算法思维而缺乏事实训练的体现，成了两足复读机，读下这本书至少还能掌握谷歌书籍词频与ProQuest这俩工具与一些历史轶事。

## 《多面一体》

- 体细胞与微生物数量类似

- 进化岛屿 微生物岛屿是人

- 母乳中的糖有些是为微生物准备的

- 讲列文虎克的故事，如何发现细菌，然后细菌学说流行，然后开始有了细菌有益说，之后出现了16sRNA，发现了古菌，之后出现了宏基因组学，最后回归列文虎克博物馆，点题350年的微生物研究

- 通过实例串联来说明微生物对植物动物然后是人的行为影响 微生物部分塑造了人

- 细菌没有好坏 与宿主互相利用 粘液里噬菌体塑造了免疫系统

- 蚊子微生物来阻止登革热

- 共生关系

- 基因横向流动

- 粪便治疗

## 《贪婪的大脑》

- 句法规则不等同于意义

- 从酵母菌 、虫子到人类 ，仅仅通过少吃点 ，至少能增长 1 / 3的寿命

- 另一个保持基因创造力的方式是死亡

- 进化的动力就是繁衍后代 ，生存居次要地位 。死亡作为一种进化手段 ，展示了繁衍与生存之间的矛盾 ：为了使基因能够更准确地反映最新的相关信息 ，有利于繁衍后代 ，有机体会毫不犹豫地放弃生存

- 进化革新最主要的来源是病毒

- 我们每个人有近 1 0 0万个黄色节杆菌元素 ，占了人类基因组的 1 0 % ，但这些 D N A序列不参与任何蛋白质编码 。没有一个有机体愿意支持这种过度的 、自私的复制行为 。但这些微小的 D N A序列成功地隐藏在染色体中 ，很难被发现 

- 进化在各个级别都会舍弃那些与生存不相关的 “想法 ” ，而保留那些准确的 、重要的 “概念 ”

- 衡量有机体复杂性更理想的标准是蛋白质的数量 ，而不是基因的数量

- 我们一些非理性的信念 （如宗教信仰 ，以及相信外星人劫持的说法 ）之所以很普遍 ，原因之一是我们坚持不懈地在信息的洪流中寻找结构和意义 

- 信息流中发现规律性和意义 ，与意识以及在生活中不断累积的丰富的 、深沉的经验密切相关

- 边缘系统和大脑皮层 ，在麻醉时处于停滞状态 ，也不可能产生意识

- 我们处于无意识状态 （如全身麻醉后的状态 ）时 ，在意识的监测下 ，我们只能隐约听到某个词 ，仅此而已 。稍微复杂一点的内容 （如词的意义 ） ，至少需要一定层次的意识参与才能破解 ，而无意识是无能为力的

- 研究无意识的最佳的方法是 ：研究一个人在全身麻醉状态下的反应

- 仅仅是无意识参与运算的学习形式根本没有任何优越性

- 无意识无法处理大多数的逻辑运算 ，不能进行因果推导 ，无法识别几乎所有的序列 。除了靠机械背诵记住的数学运算 （如乘法表 ） ，其他任何数学运算 ，无意识都无能为力

- 证明无意识优越性的实验都具有欺骗性 ，因为研究者能够很容易地向参加实验的志愿者说明统计资料和各种可能性 ，然后鼓励志愿者们改变行为方式 ，告诉他们只有这样才能在实验中有最佳的表现 ，才能使他们的意识赶上无意识

- 越来越多的证据表明 ，无意识只能处理相对简单的 、几乎不具备任何结构的信息 

- 如果我们能绝对客观地做决定 （如同我们代表一个完全陌生的人慎重考虑 ，做某个决定 ） ，那么我们会选择深思熟虑的 、有建设性的意见 ，而不会选择欠考虑的 、毁灭性的意见

- 深层的模式 ，但在做决定时只是起辅助作用 ，而不是起支配作用 。从生物学上来说 ，人类的目的是为了生存和繁衍 ，无意识为这个目标尽一切努力 ，而意识是协助无意识

- 假设突然发生一场大灾难 ，所有的科学知识都被毁灭 ，只有一个句子可以传给后代 ，什么样的句子能够以最少的词汇表达最多的信息呢 ？我认为是原子假说

- 这种情况适用于大多数 （如果不是全部的话 ）突现论的例子 （如蚂蚁的集体智慧 ，宏观经济学 ） ，积极和消极的结果在低层次相互作用 ，从而在高一层次产生更准确 、更合适的解决办法 

- 精神分裂症的标志之一是确信自己头脑里的想法不是自己的 。换句话说 ，很多精神分裂症患者相信 ，他们的某些经验至少有部分是属于别人的

- 自我意识很可能是强大的智力与丰富的意识的副产品 ，而不是智力或意识产生的原因 

- 事实上 ，许多其他物种快速记住事物的数目上限和人类一样 ，也是 3 ～ 4个

- 注意显然是意识的守门人 ；对某一内容具有完全的意识意味着 ，这一内容在进入有限的工作记忆空间时备受注意青睐 ，而这个工作记忆空间同时能够存储我们模糊地意识到的一组项目

- 关于语言本能的神经科学证据主要来自一种称作 F O X P 2的基因 。据称 ，这种基因发生突变 ，会导致选择性的语言障碍 ，尤其是不能流利地讲话 。但这种基因突变同时也导致整体的认知缺陷 ，如智力低下 ，这很可能是基因突变导致组块功能受到损伤引起的 ，而不是语言功能受到损伤引起的

- 意识在开始的时候对复杂的学习来说是必需的 ，但是在经验获取后 ，意识反而会阻碍自动的处理过程

- 盲视是一种矛盾的 、令人困惑的神经学现象 。一个人的初级视皮层 （位于大脑后部 ）受损 ，会导致失明 ，至少会有部分视域不可见 。

- 证明与人类关系稍微疏远一点的红毛猩猩是我们灵长类近亲中最聪明的 。更让人惊奇的是 ，我们 4岁大的孩子在这项实验中输给了黑猩猩 ，只有到了 6岁才能胜过黑猩猩 

- 长期冥想确实有助于更高效地完成与注意相关的任务 ，工作记忆技巧与空间处理能力也得到提高

- 只有在人类身上 ，进化的基本动力与高级的意识目标才会产生如此强烈的冲突

- 在稳定环境中存活的细菌 ，基因突变率很低 ，生活得很安全 ，缺乏革新精神

## 《博士磨练》

第一年 拿到博士资助（很重要），做项目不顺，论文被拒，放空10周，去了谷歌实习，发现兴趣要与研究契合

第二年 找其他教授合作，学会写论文，重新做了个项目，但因为属于入侵者，论文被拒，回归主课题

第三年 核心搜索算法优化做了四个月，无果；两个人合作新想法，无果，一个退学，最终发表建立在4个学生的工作上，3个退出项目；最终放弃主课题

微软实习  MIT的弱联系与发表过的论文帮助拿到了实习机会 

最好出了三篇顶级会议论文

第四年 同学比教授靠谱，在小会上发表也有重要帮助，新想法在 Berkeley 拿到尝试机会但因为插件不兼容所以失败，然后投稿

第五年 尝试新想法，结果连第四年的一起两个都被拒了，然后修改后两个都接受了，后来又做了通用CDE，放到技术论坛后很多人都在用，心态变好，在谷歌作报告并拿到实习机会，最后做了个保底项目，然后一共发表四篇一作

第六年 多尝试，总有结果，去波士顿做了最后一个项目，以相对平庸结果毕业但很满足

 	⁃	成果为王
 	⁃	输出大于输入，目标明确
 	⁃	寻找相关信息
 	⁃	创造幸运
 	⁃	参与并玩好博士游戏
 	⁃	谦虚学习前辈
 	⁃	教授也是人
 	⁃	友善
 	⁃	做一些不得不做的项目
 	⁃	拒绝导师默认设定
 	⁃	知道何时退出
 	⁃	从失败中恢复
 	⁃	跟内行合作
 	⁃	多拿报告机会
 	⁃	卖自己的观点
 	⁃	大方提供帮助
 	⁃	寻求帮助
 	⁃	表达感谢
 	⁃	想法是想法之父
 	⁃	聪明的磨练 1w小时
 	⁃	have fun and fulfilling

##《万万没想到》

- 人对不同信息的接受程度天然不一样（确认偏误，回音室效应），理性的人更不宜被说服

- Fox新闻：给观众想要的东西比给事实赚钱，贩卖肯定与认可

- 对全球变暖观点分歧最大的人恰恰对这方面了解最多

- agree to disagree 理性人讨论结果必然一致，不欢而散则有一方虚伪

- 科研最大乐趣就是被别人改变想法

- 林肯：你可以在所有时间里欺骗一部分人，也可以在一段时间里欺骗所有的人，但你不可能在所有时间欺骗所有的人

- 普通人思维区别于科学思维在于认为凡事有目的

- 电视剧常用桥段 tvtropes.org

- 有意思的东西是稀缺资源，可重复性强，编剧与编程都可以成为艺术

- 人会用短期的不健康换取高额利益

- 数据显示能够左右成绩的品质只有自控

- 意志力像体力一样是稀缺资源，做选择会消耗意志力（决策疲劳）

- 维护现有格局并遵守游戏规则的是高富帅，改变规则是屌丝的特权

- 教育的目的是摆脱现实的奴役而现在大多数人是为了适应现实改变自己

- 心理特征是天生的，经济地位越低，环境对孩子影响越大

- 思维密集度等于准备读物需要的时间除以读读物的时间

- 不管成立公司是经济繁荣还是衰退，生存概率都大概是三成

- 穷人社交圈单一，富人多样但通话时间短

- 弱联系帮助找工作，提供更丰富的信息

- 合伙要找陌生人，但强联系有安全感

- 知识分为学过与没学过及学过但没答案这三种

- 科学逻辑要自洽，更要可预测

##《智识分子》

- 人是从众且喜欢为模仿而模仿并产生级连效应

- 国家不是家庭：陌生人社会不是熟人社会，陌生人谈规则、利益与效率，熟人讲亲情，不能等而视之

- 没有免费的午餐：边际效应（不用考虑总效果，只要知道下一步临界效果就可以）总是递减的

- 人会对激励做反应：改变人的行为要通过激励或者说精神上的鼓动，调动积极性
市场是激励信号的传递方式：市场的价值信号要充分传递才能起作用

- 选民通常是无知的，但民主选举不会因此失灵，随机分布的意见会相互抵消，让占比例很小的专家意见获胜（精英统治）

- 选民喜欢小故事，投票靠的是小故事宣泄感情

- 最喜欢的小故事是不怕敌人的勇敢故事与自我救赎的奋斗故事

- 富人和所谓上流社会的道德水准低于普通人 [论文](https://www.pnas.org/content/109/11/4086.abstract)

- 社会经济地位更高的人群如果作弊是为了自己，普通人作弊为了别人 [论文](http://psycnet.apa.org/psycinfo/2015-03027-001/)

- 一个人的成就中工作业绩最不重要，重要的是与上级的关系（学术圈相对好）

- 康德式任性：只有当你纯粹是出于责任和义务去做事才是自由的，才是真正的道德

- 不做任何人、任何东西、任何感情的奴隶，做一个主人，去任性

- 康德不把任何人当工具，不欺骗任何人

- 人不应成为工具与奴隶，用智慧去挫败那些妄图玩弄别人的企图，不论是否有意识

- 歧视有两种，一种是敌意歧视，另一种是经济歧视（统计歧视，基于数据），前者在减少，后者在增加

- 弱者抱怨歧视，强者主动出击

- 选举的三围 

名义选民：对于谁当领导人无影响力 
实际选民：对领导人有实际影响力的人 如皇室成员 
胜利联盟：领导人实际长期依赖的组织 

- 真民主的核心在于胜利联盟的人数的增多

- 领导人的目标只有两个，获得权力并保住权力 

减少联盟人数方便收买，统一思想，例如国际足联 
增加名义选民，例如朝鲜 
控制收入 
回报联盟 
改革伤害联盟就会危及自身 

- 国家利益是幻觉，本质是各联盟的博弈

- 独裁体制收买少数人，民主体制收买多数人，本质都是收买

- 更多的经济发展可以换来更多的胜利联盟，体制也会因此更加民主

- 高考背后的学历是社会中的门槛而非知识传授

- 聪明学生去不去名校无影响，低收入家庭去名校改变生活

- 素质教育本质是精英教育，分层教育

- 名校多采用商业运作模式，校友捐赠是核心

- 圣贤之道多类似于中庸之道，不是和稀泥，而是认识到存在不同的都不完美的意见而协调它们

- 不平凡，不能被统计模型预测的人是英雄

- 对抗体制，学校与家长都是体制一部分

- 美国阶层严格按照种族与贫富隔离区分，不同阶层受教育完全不同，不容易超越自己父母阶层（中国的明天？） 

- 普通工人阶层强调规章流程，灌输知识（国内小学）

- 一般中产强调把事情做对，为找工作和上大学服务（国内中学）

- 专业人士阶层强调创造性与独立性（国内大学）

- 主管精英阶层强调智识并参与制定规则（研究生）

- 现代流水线教育是奴隶教育，古代贵族教育是主人教育，主动与被动不一样

- 现代教育的三个阶层: 贫民，培养工具，找工作; 中产，培养工艺品，提升个人价值; 上层，培养主人翁，改变世界

- 家庭收入水平和父母文化水平决定孩子达到什么层次

- 中国没有强烈的阶层划分，大家都在一般中产及以下混了很多年，主流是贫民文化，缺少主人翁意识

- 所谓英雄，就是超越了阶层出身，超越了周围环境，超越了性格局限，拒绝按照任何设定好的程序行事，不能被大数据预测，能给世界带来惊喜，最不像机器人的人

- 对市场做出反应是一般公司，使用供给创造新的需求是英雄企业，替用户决定

- 如果你从未失败，说明你玩的不够高级

- 考试不能太深太广，必然诉诸俗套

- 数据分析真正作用是让好东西迅速流行并消亡

- 数学>物理>化学>生物=医学>经济学＝心理学＝政治学

- 有人声称自己大一统且充满自信，别搭理他

- 取悦民众不见得合算，越富裕，幸福感增长越慢

- 人可以被数字化预测且越来越准

- 技术进步往往减少就业

- 世界上总工资买不起总产品

- 机器人是彻底的经验主义者

- 合弄制：以工作为本，面向问题组织人

- 前期知道问题在哪里可以设计制度规避，不用自由生长

- 创新是坚持市场经济的唯一理由

- 市场不是无限大的但物质过剩

- 资本需要运转，需要有可以投资的项目

- 鼓励消费真正促进经济发展

- 消费文化促进社会变革

## 《the offical preppy handbook》

### 从出生到工作

- 有个五月花号的先祖
- 一定申请私校
- 继承花体字与旧家具
- 出生，申请，结婚都是规划好的
- 起昵称
- 不装饰就是最好的装饰
- 所有的东西都有用
- 用鸭子做图腾，象征打猎
- 家里不凌乱要请佣人
- 十岁前开始学钢琴
- 女孩学芭蕾
- 七岁前一周一次学跳舞，会狐步、华尔兹与恰恰
- 学法语
- 学网球
- 学航海
- 一周一次骑马
- 参加夏令营
- 家里养狗，起名用酒名或圣经人物
- 上高中寄宿
- 去单一性别学校
- 25岁前没有性生活
- 1/8用来学习，其余用来社交
- 广泛参与课外活动
- 抽烟不允许但为了以后社交必学
- 作弊但不要被抓
- 存在波西米亚式学校，放荡不羁
- 过滑雪假日是精英标志，器材贵，早接触技能才好，不舒服，不方便，危险
- 上大学靠特别的体育项目，讨好能带去学校参观的老师
- 藤校最preppy，但preppy并不代表藤校，高私立高中学生的文理学院更佳
- 大学生活是最自由的四年
- 不选早课晚课，保证一定图书馆读书时间来在课堂上炫耀学识
- 住的离学校近，加入兄弟会，保持高中节奏
- 玩长曲棍球与壁球，这两个需要大量训练才能玩好，证明自己运动员精神
- 出入合唱团、慈善活动、音乐会、艺术展、电影节、网球俱乐部见老朋友
- 专业选英语、历史、经济或古罗马文学或建筑，不能选比较容易的地质、人类学还有心理学，不能选太深奥的例如比较文学、哲学、语言学，不能选太职业化的例如工程、化学、数学
- C就可以但不能F
- 划船、学习还有聚会不可兼得，明显要划掉一个
- 精英喜欢坏女人但只跟精英结婚，精英男性认为精英女性有两类：可以结婚的跟无性的，精英男性找精英妻子要完美，无性的让精英男性感到恐惧
- 精英的亲密关系绝不能放在面上，即使所有人都知道，女性不滥交，男性不轻浮（只针对女性精英）
- 标准流程：礼貌亲吻-真接吻-喝醉后做爱-女生家过夜-面上公开
- 参加聚会衣着要随意，不露怯，有酒量，只喝一种利口酒，啤酒最安全，白葡萄酒女生喝，琴酒是毒药，苏格兰威士忌适合酒鬼
- 精英要有怪癖
- 毕业后做律师、股票经纪人、业务代表、投行、艺术品交易商、收藏家、编辑、修家具、园艺家、大学招生员、职业网球选手、农场主、木匠（要有哲学博士学位）、NGO、快艇设计者、慈善家或没用的人（可做大脑手术）
- 三种海外（欧洲）镀金头衔：罗氏奖学金、富布莱特奖学金、Keasbey奖学金
- 一到三个月的海外旅行

### 金钱观

- 不谈自己钱，可谈别人钱的来源
- 20岁拿到信托前对信托人保持节俭
- 做慈善
- 花钱一掷千金或一毛不拔
- 不在意金额
- 不带现金，或借或欠
- 不要抢着付账单，如果要请客去你家的店
- 孩子的钱必须自己赚出来（家务）
- 不论有没有账户在所有店赊账，漫不经心留下名字与地址
- 不到完全报废不换任何东西
- 快速高频付所有小额账单，例如出租、饮料
- 不要说 wealthy 说 rich
- 保持欠债

###  价值观

- 延续性，有家规
- 低调
- 有教养风度
- 会喝酒有酒量
- 举重若轻
- 参加竞技运动，装备越贵越好
- 自律
- 参与公益事业

### 舞会首次亮相（debut）

- 富家女初次参与公众社交舞会
- 能收到邀请
- 有得体的陪同人
- 白色着装、手套、白鞋还有珍珠，不能重复穿
- 六月或圣诞节，几周
- 场合是慈善舞会

### 书单（主要关于校园生活）

- 麦田里的守望者
- 独自和解
- 一个好学校
- 简·布罗迪小姐的青春
- 汤姆求学记
- 万世师表
- 茶与同情
- 人间天堂
- 爱的故事
- 衰落与瓦解
- 校长
- 贾斯丁的校长
- 好时光/坏时光
- 约翰·契弗的故事集
- 劳伦斯威尔故事集
- 乌龙女校

### 着装原则

- 保守，多年风格一致
- 整洁，衬衣入裤，鞋亮，袜子笔直，毛衣肘部加厚
- 注意细节，面料配饰搭配
- 务实，雨衣防雨，冬装保暖，领子带扣不外翻
- 高品质，手工打造
- 用需要打理的天然面料
- 英式崇拜
- 不在意颜色，除了一些亚文化
- 运动派，随时打猎的行头
- 男女穿着类似，中性
- 布料可以有花纹，可以是花或重复的图形
- 衣物有姓名首字母绣花，可以显示品位，宁缺毋滥
- 男士绣花在衬衫左边
- 绣花要很难发现
- 海军蓝最保守，红绿表示运动员
- 女性学妈准没错，可以穿男装，海军蓝，不穿黑，别人的衣服，有品位（盛装后摘掉一款首饰），有层次
- 女鞋有两种，工作鞋与休闲鞋（没有皮质鞋底），鞋跟不超过2.5英寸（6.35厘米），颜色保守（hot pink）
- 女士衬衫必须纯棉，必须扎腰
- 连衣裙选黑色吊带，简洁大方舒适
- 裙子用来掩饰而不是显示女性体态
- 裤子要宽松，低腰，笔直
- 配饰可以女性化，永不摘掉首饰，即使要运动
- 毛衣永不嫌多，上下收口
- 男士基本款永不变，运动场合与社交场合不穿袜子，烟是首饰，可以有家族戒指，袖扣小而精致，有领针，剃须，头发短而保守，室内穿室外装，纯棉四角裤，有层次
- 男士外观先看鞋
- 衬衣白色居多，但BB的粉色最好，不存在短袖衬衣只有长袖卷起，polo两颗扣不用系，不穿天鹅绒
- 长裤修边，绝不打折，口袋跟裤缝重合，窄腰带
- 西服外套自然肩，三扣，有翻袋
- 配饰不闪亮但精致用心
- 准备夏装应对休闲场合
- 外套只用在外面，精英长居室内
- 绿粉搭配是精英范

### 城市安居

- 居闹市若郊区，只跟精英混
- 继续参与聚会，利口酒与冰不能断，男女比2:1，不要装，不要创新，永远准备好跳舞
- 周五晚上过普通人生活，吃民族小吃、看棒球赛、去工薪酒吧、城市漫游、去朋克摇滚俱乐部
- 周六晚上几组朋友去女士家小聚，然后去夜店跳舞
- 周日一点吃早午饭，饮料主题是血色玛莉（伏特加/琴酒+冰+调料+柠檬+番茄汁或V8蔬菜汁），吃完后逛博物馆或看电影
- 休假春秋去滑雪，冬天去热带，夏天看文化
- 当周围没有单身朋友时就该结婚了，订婚要登报纸，婚礼聚会伴娘会很累，着重与天色搭配，礼物多是餐具，婚礼持续两天，在新郎家院子的帐篷里进行，播放老式音乐，第二天报纸宣告，小心闹洞房的恶作剧。

### 乡村俱乐部

- 30岁左右卖掉城市两居买郊区大别墅，开SUV赶火车，养娃循环开启
- 老公学园艺打高尔夫玩老爷车，女士参加太太局，做家务，上各种课程
- 成年人重心在于维护既有利益，努力工作努力玩，如果二选一，努力玩
- 参加乡村俱乐部，也就是老男孩社交网，打高尔夫、游泳、去海滩、打网球、露天烧烤、俱乐部聚餐、更衣室聊八卦
- 办事托关系
- 在校友重聚时加入优秀校友是精英最高荣誉，校友会是关系网核心
- 做慈善与公益活动，支持当地俱乐部博物馆与公益组织，主要方式是开舞会、主题展、义卖、拍卖、古董展
- 出行车只能是红蓝绿金属色，后视镜无挂饰
- 买度假屋或小岛，海边或山上，有游艇玩航海
- 精英有口音，兴奋不起来、玩世不恭、有生活情趣、喜欢社交、有自己的黑话、热心肠且有阅历

##《metaphors we live by》

最近终于读完了《metaphors we live by》，这本书在过去的六七年里一直存在我的 Kindle、电脑还有手机里，无论多么精神多么没有睡意，读这本书几页都会很快睡过去，堪称催眠王中王。最开始推荐的那货说这本书一两个小时就能翻完，我猜他的翻完意思是翻个身完美睡过去。而我还记得第一次读是在火车硬卧车厢，当时深夜晃得很厉害下铺还聊天，然后一页没读完再睁眼天都亮了。这次我特意拿出一整天读这本书，然后中间睡过去七次，有时是读睡过去，有时是记笔记睡过去，最后是灌着红牛生生读完的。

不过，书是好书，解答了我一个困惑。我对认知语言学是没啥概念的，但当年学科学哲学时老师就说有个流派最后去搞语义学去了，大概意思是当前的语言不论语系都是解决生存问题发展来的而不是逻辑自洽的，其中描述上的漏洞就是科学永远无法填的坑，甚至因为学术交流根植于这种不完美的语义系统，连发觉都很困难。数理逻辑虽然严密，但自打出了哥德尔不完备定理后也就那样，因为语义限制了认知，科学跟实在就很难真正意义连到一起。

我当时的困惑在于不清楚人的语义系统是咋构建出来的，不论学语文还是英语，语法体系都是相对严密的，严密到根本意识不到这玩意为啥是这样。我们认识一个新事物，主要是通过抽象与同义过程来实现，例如计算机这个名词的核心就是计算这个任务用机器来完成，用计算机指代这堆机器就是抽象了其核心特点并用更基础的概念“计算”与“机”进行了组合定义。在这个定义体系下，所有描述都是必要且精准的，更重要的在于是“客观”的。其实只有人开始追求“客观”，才能出现交流，因为这意味着交流双方使用了通用概念。

认知系统需要解决基础、结构、相关与定义问题，而作者认为这些并不是独立的，是通过隐喻来构建而不是基于定义的。所谓隐喻，就是利用相似性来认识事物的过程。例如，当我们说浪费时间时，时间这个概念是不存在浪费的表述的，我们用浪费，是把时间当成了生存资源来叙述的，这里的隐喻其实是我们用已知的东西来理解其他东西或概念的某个属性。从认识角度看，我们一定是从已知来认识未知的而不是凭空脑子里就出现一套概念体系。

在作者看来，有三种隐喻形式，一种是系统隐喻，一种是空间隐喻，另一种是本体隐喻。系统隐喻是结构化的事物类比，例如辩论就是战争，辩论中我们会攻击对方的论点。空间隐喻是方向化感知对事物的比喻，存在文化差异，好就是上，不好就是下，例如我们说进步其实就是用方向上前进来隐喻变好的过程。至于本体隐喻可以把概念具像化、容器化或拟人化，例如我们会说愤怒操纵了人们，但愤怒只是一个情绪概念不会有动作，我们在描述时其实是概念拟人化了。这三类隐喻几乎无处不在，例如我用“无处不在”时，就把隐喻当成了一个物理实体。这也是我最佩服作者的地方，他这么一说才发现日常交流中真的是大量使用了隐喻。与隐喻类似的一个概念是转喻，我们用隐喻的场景通常是为了理解某个过程或描述某个过程，而转喻则不含辅助理解的功能，仅仅就是用其他概念来替代。例如用部分特征指代整体，例如计算机里计算只是一部分功能，还有存储展示等功能，但提及计算机你就会意识到其实体是什么而不必过多解释，甚至也没法过多解释。

我们用隐喻来学习或认识世界的过程是通过辨识隐喻间的差异来实现的，例如我们描述高兴，可以是像糖一样甜蜜，也可以是中彩票后的感觉，这些体验交织后我们自己会更准确描述高兴对自己的含义，很多新概念是用其他已有概念来部分说明的。也就是说，作者认为隐喻是一种基于个人经验的主观认知方式，不能保持通用性。而语言系统其实从来都不保证通用性，这点最典型的例子就是缩写，COS可以是动漫扮演，可以是余弦函数，也可以是统计之都，我们天天用的语言系统根本不保证精确性，只是我们大脑习惯了用语境上下文来进行本能判断而作为使用者很难意识到。

那么已有概念从哪来呢？作者认为是伴随个人成长来的，正如内陆国家语言没有描述海洋的词汇，每个人的已有概念都是从身边开始构建的。最基础的就是空间感，上下左右前后，婴幼儿在瞎折腾手脚时就有基础的空间感知，接触到物体就有物理质地感觉，通过把自身情感感受与经验的相关，每个个体就构建了属于自己的隐喻关系。隐喻基础没有谁更基础之分，但概念化过程存在更基础的隐喻，也就是你最先感受到啥就更容易在这个感受基础上构建对更新事物的理解。基础隐喻很大程度基于经验与经验背后的文化，而如果经验与文化有差别，那么隐喻关系的理解也收到影响。所有概念都是新兴事物及新兴事物产生的隐喻概念构成的，是混合的，部分隐喻，部分新兴，用来进行区别概念的不同。隐喻里的定义是基于经验的天然种类，并非完全客观，是开放的，共同经验的。我们能交流不是因为我们用了同一套词典，而是我们在用同一个发音时背后隐喻的场景是一致的。很多所谓可意会不可言传的感受其实是没有词指代但背后的经验场景是共通点，人类创立词汇与概念来传承知识，但知识的理解说到底还得有个人经验或隐喻背书，否则就是个空洞的概念。而经验存在相干的结构，是多维形状的新兴组合，隐喻有助于经验在不同人的认知体系里互相通用。而理解是认知的核心，是审美的，审美存在趋同，不论是本能还是文化作用。隐喻不同于主观客观，更多是经验综合，西方传统对客观性的追求限制了对世界的认识，而通过隐喻角度则可以放开了认识探索世界。

语言系统里因果关系也是通过隐喻来构建的。因果关系起源于典型直接操纵的聚合，典型直接操纵是可以分析为具体自然发生特性的形状，因果概念的新兴事物内核可被多种部分精密隐喻所描述。很多概念好比忒修斯的船，不断的转述与发展甚至可以增加或派生出新的含义出来，而原有含义则消逝了。例如 SPAM 其实就是战争期间午餐肉的一个品牌（现在也有），但因为美国兵认为太难吃就等同于垃圾，而后来竟然就成了垃圾邮件的代名词。其实过去二十年信息技术的发展中大量使用了已有概念，然后特化成了专用名词，例如bug、cookies、e-mail等，我们的所谓创新从隐喻角度看其实非常有限，如果你清楚很多词背后的故事与其结构性隐喻的背景，就不会认为这个词是凭空出现在某个专业领域的。

书中另一个有意思的点在于对形式与内容的讨论，人造语义系统经常是严格区分形式与内容的，严格拒绝冗余，例如编程语言。但我们先天配的认知语言系统却经常是混合形式内容的，例如描述多少时，我们会用多，很多，最多来不重不漏描述量，但日常交流时，我们会用“很多很多很多”这种重复语句来寄托多的程度与背后情感，冗余的形式实际创造了更多的内容，而这些偏个人感受的东西在语义或形式逻辑里经常是不被承认的，或者被当成了缺点。然而在作者看来，如果我们还想更好地面对与认识世界中的未知，就不能拒斥掉形式内容的内在一致性与互补性，而隐喻既可以作为形式基础，也可以作为内容基础。整体上作者是站在隐喻的内核上重新定义了语言学的构建过程，去掉了里面死板僵化的概念，指出了现代语言体系中的伪客观性，最后收敛到了经验综合过程之中，自成一家之言。

我读这本书最大感受就是这本书有个解放思想的内核。之前我无数次表达了对专业术语体系的反感，很重要的一点在于我发现他们是为了小团体利益把简单直白的概念复杂化了，读了这本书我大概明白他们术语背后的隐喻内核了，说白了就是除了基础概念外专业术语体系中使用了大量的行业内隐喻，这是没有行业经验无法理解的，但如果有类似体验其实理解并不困难，但术语体系则充当了分割经验体系的墙，提高了互通门槛。这个门槛要么导致行业僵化，要么走向神秘化宗教化，搞些只可信仰不可理解的教条。从隐喻角度看，我们认识世界是一个不断经验综合的过程，既有过往经验体会，也通过组合隐喻来描述新事物，从已知走向未知而不是空降一套术语形式。这个认知系统不完美但却从未停止发展，其并不关注判断而更多关注理解，这样的认识过程就不会僵化。所谓的通用认知体系只是一个理想产物，现实中的认知从来都是打着个人经验烙印的，但因为共同的隐喻经验使交流成为可能。我感觉作者其实是在努力调和语言学里的理性主义与经验主义，用更多思考来替代冰冷的价值判断。其实我也读过一些顽固分子特别是市场原教旨主义的人写的书，因为缺乏对其他理论的认识，很多批判其实都是想像出来的，符号化妖魔化严重，价值判断上明显双标，这种人的思考永远逃不出其已经认可为绝对真理的价值体系，也因此没法针对新事实提出建设性的解决方案。而在隐喻的语义学体系中，真理是依赖于隐喻系统定义的认知系统，也因此根本就不保证绝对性，就像科学探索一样，永远在路上，永远在质疑，永远在发展。

希望读到这你还没睡过去。
