project:
  type: book
  output-dir: _book
format:
  html:
    theme: journal
    code-copy: true
  pdf:
    include-in-header:
        - text: |
            \usepackage{booktabs}
            \usepackage{ctex}
            \renewcommand{\chaptername}{章}
book:
  title: "自然生活的数学原理"
  author: "yufree"
  date: last-modified
  language: "zh"
  description: "又名《新毕达哥拉斯主义》"

  page-footer:
    left: |
      <a href="./">自然生活的数学原理</a>
    right: |
      "本书由<a href="https://quarto.org/">Quarto</a>生成."
  site-url: https://yufree.github.io/lifeguide/
  repo-url: https://github.com/yufree/lifeguide
  repo-actions: [edit,issue]
  downloads: [pdf]

  chapters:
    - index.qmd
    - 01-cloth.qmd
    - 02-food.qmd
    - 03-rental.qmd
    - 04-traffic.qmd
    - 05-financial.qmd
    - 06-interest.qmd
